; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -passes=dyncastopt -range-check-threshold=10 -S < %s | FileCheck %s
;
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

@_ZTVN10__cxxabiv117__class_type_infoE = external global [0 x ptr]
@_ZTS1A = internal constant [3 x i8] c"1A\00", align 1
@_ZTI1A = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), ptr @_ZTS1A }, align 8
@_ZTVN10__cxxabiv120__si_class_type_infoE = external global [0 x ptr]
@_ZTS2B1 = internal constant [4 x i8] c"2B1\00", align 1
@_ZTI2B1 = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS2B1, ptr @_ZTI1A }, align 8
@_ZTS2B2 = internal constant [4 x i8] c"2B2\00", align 1
@_ZTI2B2 = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS2B2, ptr @_ZTI1A }, align 8
@_ZTV1C = internal unnamed_addr constant { [4 x ptr], [4 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI1C, ptr null, ptr null], [4 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr @_ZTI1C, ptr null, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !5, !vcall_visibility !7
@_ZTVN10__cxxabiv121__vmi_class_type_infoE = external global [0 x ptr]
@_ZTS1C = internal constant [3 x i8] c"1C\00", align 1
@_ZTI1C = internal constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv121__vmi_class_type_infoE, i64 2), ptr @_ZTS1C, i32 1, i32 2, ptr @_ZTI2B1, i64 2, ptr @_ZTI2B2, i64 4098 }, align 8
@_ZTV2B1 = internal unnamed_addr constant { [4 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI2B1, ptr null, ptr null] }, align 8, !type !0, !type !2, !vcall_visibility !7
@_ZTV1A = internal unnamed_addr constant { [4 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI1A, ptr null, ptr null] }, align 8, !type !0, !vcall_visibility !7
@_ZTV2B2 = internal unnamed_addr constant { [4 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI2B2, ptr null, ptr null] }, align 8, !type !0, !type !6, !vcall_visibility !7
@_ZTS1D = internal constant [3 x i8] c"1D\00", align 1
@_ZTI1D = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1D, ptr @_ZTI1C }, align 8
@_ZTV1D = internal unnamed_addr constant { [4 x ptr], [4 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI1D, ptr null, ptr null], [4 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr @_ZTI1D, ptr null, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !4, !type !5, !vcall_visibility !7
declare ptr @__dynamic_cast(ptr, ptr, ptr, i64)

define internal ptr @_Z7dest_B2P1A(ptr noundef readonly %a) local_unnamed_addr #3 {
; CHECK-LABEL: define internal ptr @_Z7dest_B2P1A(
; CHECK-SAME: ptr noundef readonly [[A:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[DYNAMIC_CAST_END:%.*]], label [[LOAD_BLOCK:%.*]]
; CHECK:       load_block:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    br label [[CHECK_POINT_0:%.*]]
; CHECK:       check_point.0:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV2B2, i64 16)
; CHECK-NEXT:    br i1 [[TMP1]], label [[HANDLE_OFFSET:%.*]], label [[CHECK_POINT_1:%.*]]
; CHECK:       check_point.1:
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1C, i64 48)
; CHECK-NEXT:    br i1 [[TMP2]], label [[HANDLE_OFFSET]], label [[CHECK_POINT_2:%.*]]
; CHECK:       check_point.2:
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1D, i64 48)
; CHECK-NEXT:    br i1 [[TMP3]], label [[HANDLE_OFFSET]], label [[DYNAMIC_CAST_NOTNULL:%.*]]
; CHECK:       handle_offset:
; CHECK-NEXT:    br label [[DYNAMIC_CAST_NOTNULL]]
; CHECK:       dynamic_cast.notnull:
; CHECK-NEXT:    [[TMP5:%.*]] = phi ptr [ null, [[CHECK_POINT_2]] ], [ [[A]], [[HANDLE_OFFSET]] ]
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP6:%.*]] = phi ptr [ [[TMP5]], [[DYNAMIC_CAST_NOTNULL]] ], [ null, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret ptr [[TMP6]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI2B2, i64 0) #11
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %entry, %dynamic_cast.notnull
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

; TODO: optimize this case
define internal ptr @select(ptr noundef readonly %a, i1 %c) local_unnamed_addr #3 {
; CHECK-LABEL: define internal ptr @select(
; CHECK-SAME: ptr noundef readonly [[A:%.*]], i1 [[C:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[DYNAMIC_CAST_END:%.*]], label [[DYNAMIC_CAST_NOTNULL:%.*]]
; CHECK:       dynamic_cast.notnull:
; CHECK-NEXT:    [[S:%.*]] = select i1 [[C]], ptr @_ZTI2B1, ptr @_ZTI2B2
; CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr @__dynamic_cast(ptr nonnull [[A]], ptr nonnull @_ZTI1A, ptr [[S]], i64 0)
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP2:%.*]] = phi ptr [ [[TMP1]], [[DYNAMIC_CAST_NOTNULL]] ], [ null, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret ptr [[TMP2]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %s = select i1 %c, ptr @_ZTI2B1, ptr @_ZTI2B2
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr %s, i64 0) #11
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %entry, %dynamic_cast.notnull
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}
!0 = !{i64 16, !"_ZTS1A"}
!1 = !{i64 16, !"_ZTS1C"}
!2 = !{i64 16, !"_ZTS2B1"}
!3 = !{i64 48, !"_ZTS2B2"}
!4 = !{i64 16, !"_ZTS1D"}
!5 = !{i64 48, !"_ZTS1A"}
!6 = !{i64 16, !"_ZTS2B2"}
!7 = !{i64 1}
