; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -enable-negative-test -passes=dyncastopt < %s | FileCheck %s
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

@_ZTI1B = hidden constant { ptr, ptr, ptr } { ptr null, ptr null, ptr null }, align 8
@_ZTI1A = hidden constant { ptr, ptr } { ptr null, ptr null }, align 8
@_ZTI1C = hidden constant { ptr, ptr, ptr } { ptr null, ptr null, ptr null }, align 8
@_ZTI1D = hidden constant { ptr, ptr, ptr } { ptr null, ptr null, ptr null }, align 8
@_ZTV1B = hidden constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1B, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !vcall_visibility !4
@_ZTV1C = hidden constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1C, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !5, !type !6, !vcall_visibility !4
@_ZTV1D = hidden constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1D, ptr null] }, align 8, !type !0, !type !1, !type !7, !type !8, !vcall_visibility !4

; Function Attrs: mustprogress noinline uwtable
define hidden noundef i32 @_Z4testP1A(ptr noundef %a) {
; CHECK-LABEL: define hidden noundef i32 @_Z4testP1A(
; CHECK-SAME: ptr noundef [[A:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[CLEANUP:%.*]], label [[LOAD_BLOCK:%.*]]
; CHECK:       load_block:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    br label [[CHECK_POINT_0:%.*]]
; CHECK:       check_point.0:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ne ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1D, i64 16)
; CHECK-NEXT:    br i1 [[TMP1]], label [[HANDLE_OFFSET:%.*]], label [[DYNAMIC_CAST_END:%.*]]
; CHECK:       handle_offset:
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP2:%.*]] = phi ptr [ null, [[CHECK_POINT_0]] ], [ [[A]], [[HANDLE_OFFSET]] ]
; CHECK-NEXT:    [[TOBOOL_NOT:%.*]] = icmp eq ptr [[TMP2]], null
; CHECK-NEXT:    br i1 [[TOBOOL_NOT]], label [[CLEANUP]], label [[IF_THEN:%.*]]
; CHECK:       if.then:
; CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP2]], align 8
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[VTABLE]], align 8
; CHECK-NEXT:    [[CALL:%.*]] = tail call noundef i32 [[TMP3]](ptr noundef nonnull align 8 dereferenceable(8) [[TMP2]])
; CHECK-NEXT:    br label [[CLEANUP]]
; CHECK:       cleanup:
; CHECK-NEXT:    [[RETVAL_0:%.*]] = phi i32 [ [[CALL]], [[IF_THEN]] ], [ 0, [[DYNAMIC_CAST_END]] ], [ 0, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret i32 [[RETVAL_0]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %cleanup, label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1B, i64 0)
  %tobool.not = icmp eq ptr %1, null
  br i1 %tobool.not, label %cleanup, label %if.then

if.then:                                          ; preds = %dynamic_cast.end
  %vtable = load ptr, ptr %1, align 8
  %2 = load ptr, ptr %vtable, align 8
  %call = tail call noundef i32 %2(ptr noundef nonnull align 8 dereferenceable(8) %1)
  br label %cleanup

cleanup:                                          ; preds = %if.then, %dynamic_cast.end, %entry
  %retval.0 = phi i32 [ %call, %if.then ], [ 0, %dynamic_cast.end ], [ 0, %entry ]
  ret i32 %retval.0
}

; Function Attrs: nofree nounwind memory(read)
declare ptr @__dynamic_cast(ptr, ptr, ptr, i64)

!0 = !{i64 16, !"_ZTS1A"}
!1 = !{i64 16, !"_ZTSM1AFivE.virtual"}
!2 = !{i64 16, !"_ZTS1B"}
!3 = !{i64 16, !"_ZTSM1BFivE.virtual"}
!4 = !{i64 1}
!5 = !{i64 16, !"_ZTS1C"}
!6 = !{i64 16, !"_ZTSM1CFivE.virtual"}
!7 = !{i64 16, !"_ZTS1D"}
!8 = !{i64 16, !"_ZTSM1DFivE.virtual"}
