; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 4
; RUN: opt -passes=dyncastopt -enable-negative-test=false -enable-range-check=true -S < %s | FileCheck %s
;
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

@_ZTI1A = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null }, align 8
@_ZTI1B = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1A }, align 8
@_ZTI1C = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1B }, align 8
@_ZTI1H = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1A }, align 8
@_ZTI2AA = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null }, align 8
@_ZTI2BB = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2AA }, align 8
@_ZTV1B = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1B, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !vcall_visibility !4
@_ZTV1C = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1C, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !5, !type !6, !vcall_visibility !4
@_ZTV1D = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1D, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !5, !type !6, !type !7, !type !8, !vcall_visibility !4
@_ZTI1D = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1C }, align 8
@_ZTV1E = internal constant { [4 x ptr], [3 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI1E, ptr null, ptr null], [3 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr @_ZTI1E, ptr null] }, align 8, !type !0, !type !1, !type !9, !type !10, !type !2, !type !3, !type !11, !type !12, !type !13, !type !14, !type !15, !type !16, !type !17, !type !18, !type !19, !type !20, !type !21, !type !22, !type !23, !type !24, !vcall_visibility !4
@_ZTI1E = internal constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, i32 0, i32 2, ptr @_ZTI1B, i64 2, ptr @_ZTI2BB, i64 2050 }, align 8
@_ZTV2BB = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2BB, ptr null] }, align 8, !type !25, !type !18, !type !26, !type !22, !vcall_visibility !4
@_ZTV1F = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1F, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !27, !type !28, !vcall_visibility !4
@_ZTI1F = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1B }, align 8
@_ZTV1G = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1G, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !29, !type !30, !vcall_visibility !4
@_ZTI1G = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1B }, align 8
@_ZTV1H = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1H, ptr null] }, align 8, !type !0, !type !1, !type !31, !type !32, !vcall_visibility !4
@_ZTV1I = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1I, ptr null] }, align 8, !type !0, !type !1, !type !31, !type !32, !type !33, !type !34, !vcall_visibility !4
@_ZTI1I = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1H }, align 8
@_ZTV1J = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1J, ptr null] }, align 8, !type !0, !type !1, !type !31, !type !32, !type !35, !type !36, !vcall_visibility !4
@_ZTI1J = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1H }, align 8
@_ZTV1K = weak_odr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1K, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !5, !type !6, !type !37, !type !38, !vcall_visibility !4
@_ZTI1K = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1C }, align 8
@_ZTV2CC = weak_odr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2CC, ptr null] }, align 8, !type !25, !type !18, !type !26, !type !22, !type !39, !type !40, !vcall_visibility !4
@_ZTI2CC = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2BB }, align 8
@_ZTV2DD = weak_odr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2DD, ptr null] }, align 8, !type !25, !type !18, !type !26, !type !22, !type !41, !type !42, !vcall_visibility !4
@_ZTI2DD = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2BB }, align 8
@_ZTV2EE = weak_odr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2EE, ptr null] }, align 8, !type !25, !type !18, !type !26, !type !22, !type !43, !type !44, !vcall_visibility !4
@_ZTI2EE = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2BB }, align 8

;.
; CHECK: @_ZTI1A = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null }, align 8
; CHECK: @_ZTI1B = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1A }, align 8
; CHECK: @_ZTI1C = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1B }, align 8
; CHECK: @_ZTI1H = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1A }, align 8
; CHECK: @_ZTI2AA = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null }, align 8
; CHECK: @_ZTI2BB = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2AA }, align 8
; CHECK: @_ZTI1D = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1C }, align 8
; CHECK: @_ZTI1E = internal constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, i32 0, i32 2, ptr @_ZTI1B, i64 2, ptr @_ZTI2BB, i64 2050 }, align 8
; CHECK: @_ZTV2BB = internal constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2BB, ptr null] }, align 8, !type [[META0:![0-9]+]], !type [[META1:![0-9]+]], !type [[META2:![0-9]+]], !type [[META3:![0-9]+]], !vcall_visibility [[META4:![0-9]+]]
; CHECK: @_ZTI1F = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1B }, align 8
; CHECK: @_ZTI1G = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1B }, align 8
; CHECK: @_ZTI1I = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1H }, align 8
; CHECK: @_ZTI1J = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1H }, align 8
; CHECK: @_ZTI1K = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI1C }, align 8
; CHECK: @_ZTV2CC = weak_odr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2CC, ptr null] }, align 8, !type [[META0]], !type [[META1]], !type [[META2]], !type [[META3]], !type [[META5:![0-9]+]], !type [[META6:![0-9]+]], !vcall_visibility [[META4]]
; CHECK: @_ZTI2CC = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2BB }, align 8
; CHECK: @_ZTV2DD = weak_odr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2DD, ptr null] }, align 8, !type [[META0]], !type [[META1]], !type [[META2]], !type [[META3]], !type [[META7:![0-9]+]], !type [[META8:![0-9]+]], !vcall_visibility [[META4]]
; CHECK: @_ZTI2DD = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2BB }, align 8
; CHECK: @_ZTV2EE = weak_odr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2EE, ptr null] }, align 8, !type [[META0]], !type [[META1]], !type [[META2]], !type [[META3]], !type [[META9:![0-9]+]], !type [[META10:![0-9]+]], !vcall_visibility [[META4]]
; CHECK: @_ZTI2EE = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, ptr @_ZTI2BB }, align 8
; CHECK: @_ZTV1B.merged = constant %0 { { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1B, ptr null] }, { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1C, ptr null] }, { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1D, ptr null] }, { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1K, ptr null] }, { [4 x ptr], [3 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI1E, ptr null, ptr null], [3 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr @_ZTI1E, ptr null] }, { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1F, ptr null] }, { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1G, ptr null] } }, !type [[META11:![0-9]+]], !type [[META12:![0-9]+]], !type [[META13:![0-9]+]], !type [[META14:![0-9]+]], !type [[META15:![0-9]+]], !type [[META16:![0-9]+]], !type [[META17:![0-9]+]], !type [[META18:![0-9]+]], !type [[META19:![0-9]+]], !type [[META20:![0-9]+]], !type [[META21:![0-9]+]], !type [[META22:![0-9]+]], !type [[META23:![0-9]+]], !type [[META24:![0-9]+]], !type [[META25:![0-9]+]], !type [[META26:![0-9]+]], !type [[META27:![0-9]+]], !type [[META28:![0-9]+]], !type [[META29:![0-9]+]], !type [[META30:![0-9]+]], !type [[META31:![0-9]+]], !type [[META32:![0-9]+]], !type [[META33:![0-9]+]], !type [[META34:![0-9]+]], !type [[META35:![0-9]+]], !type [[META36:![0-9]+]], !type [[META37:![0-9]+]], !type [[META38:![0-9]+]], !type [[META39:![0-9]+]], !type [[META40:![0-9]+]], !type [[META41:![0-9]+]], !type [[META42:![0-9]+]], !type [[META43:![0-9]+]], !type [[META44:![0-9]+]], !type [[META45:![0-9]+]], !type [[META46:![0-9]+]], !type [[META47:![0-9]+]], !type [[META48:![0-9]+]], !type [[META49:![0-9]+]], !type [[META50:![0-9]+]], !type [[META51:![0-9]+]], !type [[META52:![0-9]+]], !type [[META53:![0-9]+]], !type [[META54:![0-9]+]], !type [[META55:![0-9]+]], !type [[META56:![0-9]+]], !type [[META57:![0-9]+]], !type [[META58:![0-9]+]], !type [[META59:![0-9]+]], !type [[META60:![0-9]+]], !type [[META61:![0-9]+]], !type [[META62:![0-9]+]], !type [[META63:![0-9]+]], !type [[META64:![0-9]+]], !type [[META65:![0-9]+]], !type [[META66:![0-9]+]], !type [[META67:![0-9]+]], !type [[META68:![0-9]+]], !vcall_visibility [[META4]], !vcall_visibility [[META4]], !vcall_visibility [[META4]], !vcall_visibility [[META4]], !vcall_visibility [[META4]], !vcall_visibility [[META4]], !vcall_visibility [[META4]]
; CHECK: @_ZTV1H.merged = constant %1 { { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1H, ptr null] }, { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1I, ptr null] }, { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1J, ptr null] } }, !type [[META11]], !type [[META12]], !type [[META69:![0-9]+]], !type [[META70:![0-9]+]], !type [[META15]], !type [[META16]], !type [[META71:![0-9]+]], !type [[META72:![0-9]+]], !type [[META73:![0-9]+]], !type [[META74:![0-9]+]], !type [[META21]], !type [[META22]], !type [[META75:![0-9]+]], !type [[META76:![0-9]+]], !type [[META77:![0-9]+]], !type [[META78:![0-9]+]], !vcall_visibility [[META4]], !vcall_visibility [[META4]], !vcall_visibility [[META4]]
; CHECK: @_ZTV1B = weak_odr hidden alias { [3 x ptr] }, ptr @_ZTV1B.merged
; CHECK: @_ZTV1C = weak_odr hidden alias { [3 x ptr] }, getelementptr inbounds (%0, ptr @_ZTV1B.merged, i32 0, i32 1)
; CHECK: @_ZTV1D = weak_odr hidden alias { [3 x ptr] }, getelementptr inbounds (%0, ptr @_ZTV1B.merged, i32 0, i32 2)
; CHECK: @_ZTV1K = weak_odr hidden alias { [3 x ptr] }, getelementptr inbounds (%0, ptr @_ZTV1B.merged, i32 0, i32 3)
; CHECK: @_ZTV1E = weak_odr hidden alias { [4 x ptr], [3 x ptr] }, getelementptr inbounds (%0, ptr @_ZTV1B.merged, i32 0, i32 4)
; CHECK: @_ZTV1F = weak_odr hidden alias { [3 x ptr] }, getelementptr inbounds (%0, ptr @_ZTV1B.merged, i32 0, i32 5)
; CHECK: @_ZTV1G = weak_odr hidden alias { [3 x ptr] }, getelementptr inbounds (%0, ptr @_ZTV1B.merged, i32 0, i32 6)
; CHECK: @_ZTV1H = weak_odr hidden alias { [3 x ptr] }, ptr @_ZTV1H.merged
; CHECK: @_ZTV1I = weak_odr hidden alias { [3 x ptr] }, getelementptr inbounds (%1, ptr @_ZTV1H.merged, i32 0, i32 1)
; CHECK: @_ZTV1J = weak_odr hidden alias { [3 x ptr] }, getelementptr inbounds (%1, ptr @_ZTV1H.merged, i32 0, i32 2)
;.
define ptr @_Z4testP1A(ptr %a) {
; CHECK-LABEL: define ptr @_Z4testP1A(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[DYNAMIC_CAST_END:%.*]], label [[DYNAMIC_CAST_NOTNULL1:%.*]]
; CHECK:       dynamic_cast.notnull:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    [[CHECK_BEGIN:%.*]] = icmp uge ptr [[RUNTIME_VPTR]], @_ZTV1B.merged
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1B.merged, i64 200)
; CHECK-NEXT:    [[TMP2:%.*]] = and i1 [[CHECK_BEGIN]], [[TMP1]]
; CHECK-NEXT:    [[TMP9:%.*]] = select i1 [[TMP2]], ptr [[A]], ptr null
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP4:%.*]] = phi ptr [ [[TMP9]], [[DYNAMIC_CAST_NOTNULL1]] ], [ null, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret ptr [[TMP4]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1B, i64 0)
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %dynamic_cast.notnull, %entry
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

; Function Attrs: nofree nounwind memory(read)
declare ptr @__dynamic_cast(ptr, ptr, ptr, i64) #0

define ptr @_Z5test2P1A(ptr %a) {
; CHECK-LABEL: define ptr @_Z5test2P1A(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[DYNAMIC_CAST_END:%.*]], label [[DYNAMIC_CAST_NOTNULL1:%.*]]
; CHECK:       dynamic_cast.notnull:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    [[CHECK_BEGIN:%.*]] = icmp uge ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1B.merged, i64 24)
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1B.merged, i64 96)
; CHECK-NEXT:    [[TMP2:%.*]] = and i1 [[CHECK_BEGIN]], [[TMP1]]
; CHECK-NEXT:    [[TMP5:%.*]] = select i1 [[TMP2]], ptr [[A]], ptr null
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP4:%.*]] = phi ptr [ [[TMP5]], [[DYNAMIC_CAST_NOTNULL1]] ], [ null, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret ptr [[TMP4]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1C, i64 0)
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %dynamic_cast.notnull, %entry
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

define ptr @_Z5test1P1A(ptr %a) {
; CHECK-LABEL: define ptr @_Z5test1P1A(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[DYNAMIC_CAST_END:%.*]], label [[DYNAMIC_CAST_NOTNULL:%.*]]
; CHECK:       dynamic_cast.notnull:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    [[CHECK_BEGIN:%.*]] = icmp uge ptr [[RUNTIME_VPTR]], @_ZTV1H.merged
; CHECK-NEXT:    [[TMP1:%.*]] = icmp ule ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1H.merged, i64 72)
; CHECK-NEXT:    [[TMP2:%.*]] = and i1 [[CHECK_BEGIN]], [[TMP1]]
; CHECK-NEXT:    [[TMP3:%.*]] = select i1 [[TMP2]], ptr [[A]], ptr null
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP4:%.*]] = phi ptr [ [[TMP3]], [[DYNAMIC_CAST_NOTNULL]] ], [ null, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret ptr [[TMP4]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1H, i64 0)
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %dynamic_cast.notnull, %entry
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

define ptr @_Z5test3P2AA(ptr %a) {
; CHECK-LABEL: define ptr @_Z5test3P2AA(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[DYNAMIC_CAST_END:%.*]], label [[LOAD_BLOCK:%.*]]
; CHECK:       load_block:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    br label [[CHECK_POINT_0:%.*]]
; CHECK:       check_point.0:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV2BB, i64 16)
; CHECK-NEXT:    br i1 [[TMP1]], label [[HANDLE_OFFSET:%.*]], label [[CHECK_POINT_1:%.*]]
; CHECK:       check_point.1:
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV2CC, i64 16)
; CHECK-NEXT:    br i1 [[TMP2]], label [[HANDLE_OFFSET]], label [[CHECK_POINT_2:%.*]]
; CHECK:       check_point.2:
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV2EE, i64 16)
; CHECK-NEXT:    br i1 [[TMP3]], label [[HANDLE_OFFSET]], label [[CHECK_POINT_3:%.*]]
; CHECK:       check_point.3:
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1E, i64 48)
; CHECK-NEXT:    br i1 [[TMP4]], label [[HANDLE_OFFSET]], label [[CHECK_POINT_4:%.*]]
; CHECK:       check_point.4:
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV2DD, i64 16)
; CHECK-NEXT:    br i1 [[TMP5]], label [[HANDLE_OFFSET]], label [[DYNAMIC_CAST_NOTNULL:%.*]]
; CHECK:       handle_offset:
; CHECK-NEXT:    br label [[DYNAMIC_CAST_NOTNULL]]
; CHECK:       dynamic_cast.notnull:
; CHECK-NEXT:    [[TMP7:%.*]] = phi ptr [ null, [[CHECK_POINT_4]] ], [ [[A]], [[HANDLE_OFFSET]] ]
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP8:%.*]] = phi ptr [ [[TMP7]], [[DYNAMIC_CAST_NOTNULL]] ], [ null, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret ptr [[TMP8]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI2AA, ptr nonnull @_ZTI2BB, i64 0)
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %dynamic_cast.notnull, %entry
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}


!0 = !{i64 16, !"_ZTS1A"}
!1 = !{i64 16, !"_ZTSM1AFivE.virtual"}
!2 = !{i64 16, !"_ZTS1B"}
!3 = !{i64 16, !"_ZTSM1BFivE.virtual"}
!4 = !{i64 1}
!5 = !{i64 16, !"_ZTS1C"}
!6 = !{i64 16, !"_ZTSM1CFivE.virtual"}
!7 = !{i64 16, !"_ZTS1D"}
!8 = !{i64 16, !"_ZTSM1DFivE.virtual"}
!9 = !{i64 24, !"_ZTSM1AFivE.virtual"}
!10 = !{i64 48, !"_ZTSM1AFivE.virtual"}
!11 = !{i64 24, !"_ZTSM1BFivE.virtual"}
!12 = !{i64 48, !"_ZTSM1BFivE.virtual"}
!13 = !{i64 16, !"_ZTS1E"}
!14 = !{i64 16, !"_ZTSM1EFivE.virtual"}
!15 = !{i64 24, !"_ZTSM1EFivE.virtual"}
!16 = !{i64 48, !"_ZTSM1EFivE.virtual"}
!17 = !{i64 48, !"_ZTS2AA"}
!18 = !{i64 16, !"_ZTSM2AAFivE.virtual"}
!19 = !{i64 24, !"_ZTSM2AAFivE.virtual"}
!20 = !{i64 48, !"_ZTSM2AAFivE.virtual"}
!21 = !{i64 48, !"_ZTS2BB"}
!22 = !{i64 16, !"_ZTSM2BBFivE.virtual"}
!23 = !{i64 24, !"_ZTSM2BBFivE.virtual"}
!24 = !{i64 48, !"_ZTSM2BBFivE.virtual"}
!25 = !{i64 16, !"_ZTS2AA"}
!26 = !{i64 16, !"_ZTS2BB"}
!27 = !{i64 16, !"_ZTS1F"}
!28 = !{i64 16, !"_ZTSM1FFivE.virtual"}
!29 = !{i64 16, !"_ZTS1G"}
!30 = !{i64 16, !"_ZTSM1GFivE.virtual"}
!31 = !{i64 16, !"_ZTS1H"}
!32 = !{i64 16, !"_ZTSM1HFivE.virtual"}
!33 = !{i64 16, !"_ZTS1I"}
!34 = !{i64 16, !"_ZTSM1IFivE.virtual"}
!35 = !{i64 16, !"_ZTS1J"}
!36 = !{i64 16, !"_ZTSM1JFivE.virtual"}
!37 = !{i64 16, !"_ZTS1K"}
!38 = !{i64 16, !"_ZTSM1KFivE.virtual"}
!39 = !{i64 16, !"_ZTS2CC"}
!40 = !{i64 16, !"_ZTSM2CCFivE.virtual"}
!41 = !{i64 16, !"_ZTS2DD"}
!42 = !{i64 16, !"_ZTSM2DDFivE.virtual"}
!43 = !{i64 16, !"_ZTS2EE"}
!44 = !{i64 16, !"_ZTSM2EEFivE.virtual"}
;.
; CHECK: [[META0]] = !{i64 16, !"_ZTS2AA"}
; CHECK: [[META1]] = !{i64 16, !"_ZTSM2AAFivE.virtual"}
; CHECK: [[META2]] = !{i64 16, !"_ZTS2BB"}
; CHECK: [[META3]] = !{i64 16, !"_ZTSM2BBFivE.virtual"}
; CHECK: [[META4]] = !{i64 1}
; CHECK: [[META5]] = !{i64 16, !"_ZTS2CC"}
; CHECK: [[META6]] = !{i64 16, !"_ZTSM2CCFivE.virtual"}
; CHECK: [[META7]] = !{i64 16, !"_ZTS2DD"}
; CHECK: [[META8]] = !{i64 16, !"_ZTSM2DDFivE.virtual"}
; CHECK: [[META9]] = !{i64 16, !"_ZTS2EE"}
; CHECK: [[META10]] = !{i64 16, !"_ZTSM2EEFivE.virtual"}
; CHECK: [[META11]] = !{i64 16, !"_ZTS1A"}
; CHECK: [[META12]] = !{i64 16, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META13]] = !{i64 16, !"_ZTS1B"}
; CHECK: [[META14]] = !{i64 16, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META15]] = !{i64 40, !"_ZTS1A"}
; CHECK: [[META16]] = !{i64 40, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META17]] = !{i64 40, !"_ZTS1B"}
; CHECK: [[META18]] = !{i64 40, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META19]] = !{i64 40, !"_ZTS1C"}
; CHECK: [[META20]] = !{i64 40, !"_ZTSM1CFivE.virtual"}
; CHECK: [[META21]] = !{i64 64, !"_ZTS1A"}
; CHECK: [[META22]] = !{i64 64, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META23]] = !{i64 64, !"_ZTS1B"}
; CHECK: [[META24]] = !{i64 64, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META25]] = !{i64 64, !"_ZTS1C"}
; CHECK: [[META26]] = !{i64 64, !"_ZTSM1CFivE.virtual"}
; CHECK: [[META27]] = !{i64 64, !"_ZTS1D"}
; CHECK: [[META28]] = !{i64 64, !"_ZTSM1DFivE.virtual"}
; CHECK: [[META29]] = !{i64 88, !"_ZTS1A"}
; CHECK: [[META30]] = !{i64 88, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META31]] = !{i64 88, !"_ZTS1B"}
; CHECK: [[META32]] = !{i64 88, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META33]] = !{i64 88, !"_ZTS1C"}
; CHECK: [[META34]] = !{i64 88, !"_ZTSM1CFivE.virtual"}
; CHECK: [[META35]] = !{i64 88, !"_ZTS1K"}
; CHECK: [[META36]] = !{i64 88, !"_ZTSM1KFivE.virtual"}
; CHECK: [[META37]] = !{i64 112, !"_ZTS1A"}
; CHECK: [[META38]] = !{i64 112, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META39]] = !{i64 120, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META40]] = !{i64 144, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META41]] = !{i64 112, !"_ZTS1B"}
; CHECK: [[META42]] = !{i64 112, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META43]] = !{i64 120, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META44]] = !{i64 144, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META45]] = !{i64 112, !"_ZTS1E"}
; CHECK: [[META46]] = !{i64 112, !"_ZTSM1EFivE.virtual"}
; CHECK: [[META47]] = !{i64 120, !"_ZTSM1EFivE.virtual"}
; CHECK: [[META48]] = !{i64 144, !"_ZTSM1EFivE.virtual"}
; CHECK: [[META49]] = !{i64 144, !"_ZTS2AA"}
; CHECK: [[META50]] = !{i64 112, !"_ZTSM2AAFivE.virtual"}
; CHECK: [[META51]] = !{i64 120, !"_ZTSM2AAFivE.virtual"}
; CHECK: [[META52]] = !{i64 144, !"_ZTSM2AAFivE.virtual"}
; CHECK: [[META53]] = !{i64 144, !"_ZTS2BB"}
; CHECK: [[META54]] = !{i64 112, !"_ZTSM2BBFivE.virtual"}
; CHECK: [[META55]] = !{i64 120, !"_ZTSM2BBFivE.virtual"}
; CHECK: [[META56]] = !{i64 144, !"_ZTSM2BBFivE.virtual"}
; CHECK: [[META57]] = !{i64 168, !"_ZTS1A"}
; CHECK: [[META58]] = !{i64 168, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META59]] = !{i64 168, !"_ZTS1B"}
; CHECK: [[META60]] = !{i64 168, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META61]] = !{i64 168, !"_ZTS1F"}
; CHECK: [[META62]] = !{i64 168, !"_ZTSM1FFivE.virtual"}
; CHECK: [[META63]] = !{i64 192, !"_ZTS1A"}
; CHECK: [[META64]] = !{i64 192, !"_ZTSM1AFivE.virtual"}
; CHECK: [[META65]] = !{i64 192, !"_ZTS1B"}
; CHECK: [[META66]] = !{i64 192, !"_ZTSM1BFivE.virtual"}
; CHECK: [[META67]] = !{i64 192, !"_ZTS1G"}
; CHECK: [[META68]] = !{i64 192, !"_ZTSM1GFivE.virtual"}
; CHECK: [[META69]] = !{i64 16, !"_ZTS1H"}
; CHECK: [[META70]] = !{i64 16, !"_ZTSM1HFivE.virtual"}
; CHECK: [[META71]] = !{i64 40, !"_ZTS1H"}
; CHECK: [[META72]] = !{i64 40, !"_ZTSM1HFivE.virtual"}
; CHECK: [[META73]] = !{i64 40, !"_ZTS1I"}
; CHECK: [[META74]] = !{i64 40, !"_ZTSM1IFivE.virtual"}
; CHECK: [[META75]] = !{i64 64, !"_ZTS1H"}
; CHECK: [[META76]] = !{i64 64, !"_ZTSM1HFivE.virtual"}
; CHECK: [[META77]] = !{i64 64, !"_ZTS1J"}
; CHECK: [[META78]] = !{i64 64, !"_ZTSM1JFivE.virtual"}
;.
