; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 5
; RUN: opt -passes=dyncastopt -enable-negative-test=false -enable-range-check=true -S < %s | FileCheck %s
;
;struct A {
;  int a;
;  virtual void foo() {};
;};
;
;struct B : A {
;};
;
;struct C : B {};
;
;struct AA {
;  int b;
;  virtual void bar() {}
;};
;
;struct D : AA, B {};
;
;struct E : B {};
;
;
;B *test(A *a) {
;  return dynamic_cast<B*>(a);
;}
;
;int main() {
;  test(new D());
;  test(new E());
;  B *b = test(new C());
;  b->foo();
;}
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

@_ZTVN10__cxxabiv117__class_type_infoE = external global [0 x ptr]
@_ZTS1A = internal constant [3 x i8] c"1A\00", align 1
@_ZTI1A = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), ptr @_ZTS1A }, align 8
@_ZTVN10__cxxabiv120__si_class_type_infoE = external global [0 x ptr]
@_ZTS1B = internal constant [3 x i8] c"1B\00", align 1
@_ZTI1B = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1B, ptr @_ZTI1A }, align 8
@_ZTV1D = internal unnamed_addr constant { [3 x ptr], [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1D, ptr @_ZN2AA3barEv], [3 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr @_ZTI1D, ptr @_ZN1A3fooEv] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !4, !type !5, !type !6, !type !7, !type !8, !type !9, !type !10, !type !11, !vcall_visibility !12
@_ZTVN10__cxxabiv121__vmi_class_type_infoE = external global [0 x ptr]
@_ZTS1D = internal constant [3 x i8] c"1D\00", align 1
@_ZTS2AA = internal constant [4 x i8] c"2AA\00", align 1
@_ZTI2AA = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), ptr @_ZTS2AA }, align 8
@_ZTI1D = internal constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv121__vmi_class_type_infoE, i64 2), ptr @_ZTS1D, i32 0, i32 2, ptr @_ZTI2AA, i64 2, ptr @_ZTI1B, i64 4098 }, align 8
@_ZTV2AA = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2AA, ptr @_ZN2AA3barEv] }, align 8, !type !9, !type !10, !vcall_visibility !12
@_ZTV1B = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1B, ptr @_ZN1A3fooEv] }, align 8, !type !13, !type !1, !type !14, !type !4, !vcall_visibility !12
@_ZTV1A = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1A, ptr @_ZN1A3fooEv] }, align 8, !type !13, !type !1, !vcall_visibility !12
@_ZTV1E = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1E, ptr @_ZN1A3fooEv] }, align 8, !type !13, !type !1, !type !14, !type !4, !type !15, !type !16, !vcall_visibility !12
@_ZTS1E = internal constant [3 x i8] c"1E\00", align 1
@_ZTI1E = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1E, ptr @_ZTI1B }, align 8
@_ZTV1C = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1C, ptr @_ZN1A3fooEv] }, align 8, !type !13, !type !1, !type !14, !type !4, !type !17, !type !18, !vcall_visibility !12
@_ZTS1C = internal constant [3 x i8] c"1C\00", align 1
@_ZTI1C = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1C, ptr @_ZTI1B }, align 8

;.
; CHECK: @_ZTVN10__cxxabiv117__class_type_infoE = external global [0 x ptr]
; CHECK: @_ZTS1A = internal constant [3 x i8] c"1A\00", align 1
; CHECK: @_ZTI1A = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), ptr @_ZTS1A }, align 8
; CHECK: @_ZTVN10__cxxabiv120__si_class_type_infoE = external global [0 x ptr]
; CHECK: @_ZTS1B = internal constant [3 x i8] c"1B\00", align 1
; CHECK: @_ZTI1B = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1B, ptr @_ZTI1A }, align 8
; CHECK: @_ZTV1D = internal unnamed_addr constant { [3 x ptr], [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1D, ptr @_ZN2AA3barEv], [3 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr @_ZTI1D, ptr @_ZN1A3fooEv] }, align 8, !type [[META0:![0-9]+]], !type [[META1:![0-9]+]], !type [[META2:![0-9]+]], !type [[META3:![0-9]+]], !type [[META4:![0-9]+]], !type [[META5:![0-9]+]], !type [[META6:![0-9]+]], !type [[META7:![0-9]+]], !type [[META8:![0-9]+]], !type [[META9:![0-9]+]], !type [[META10:![0-9]+]], !type [[META11:![0-9]+]], !vcall_visibility [[META12:![0-9]+]]
; CHECK: @_ZTVN10__cxxabiv121__vmi_class_type_infoE = external global [0 x ptr]
; CHECK: @_ZTS1D = internal constant [3 x i8] c"1D\00", align 1
; CHECK: @_ZTS2AA = internal constant [4 x i8] c"2AA\00", align 1
; CHECK: @_ZTI2AA = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), ptr @_ZTS2AA }, align 8
; CHECK: @_ZTI1D = internal constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv121__vmi_class_type_infoE, i64 2), ptr @_ZTS1D, i32 0, i32 2, ptr @_ZTI2AA, i64 2, ptr @_ZTI1B, i64 4098 }, align 8
; CHECK: @_ZTV2AA = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI2AA, ptr @_ZN2AA3barEv] }, align 8, !type [[META9]], !type [[META10]], !vcall_visibility [[META12]]
; CHECK: @_ZTV1B = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1B, ptr @_ZN1A3fooEv] }, align 8, !type [[META13:![0-9]+]], !type [[META1]], !type [[META14:![0-9]+]], !type [[META4]], !vcall_visibility [[META12]]
; CHECK: @_ZTV1A = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1A, ptr @_ZN1A3fooEv] }, align 8, !type [[META13]], !type [[META1]], !vcall_visibility [[META12]]
; CHECK: @_ZTV1E = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1E, ptr @_ZN1A3fooEv] }, align 8, !type [[META13]], !type [[META1]], !type [[META14]], !type [[META4]], !type [[META15:![0-9]+]], !type [[META16:![0-9]+]], !vcall_visibility [[META12]]
; CHECK: @_ZTS1E = internal constant [3 x i8] c"1E\00", align 1
; CHECK: @_ZTI1E = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1E, ptr @_ZTI1B }, align 8
; CHECK: @_ZTV1C = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1C, ptr @_ZN1A3fooEv] }, align 8, !type [[META13]], !type [[META1]], !type [[META14]], !type [[META4]], !type [[META17:![0-9]+]], !type [[META18:![0-9]+]], !vcall_visibility [[META12]]
; CHECK: @_ZTS1C = internal constant [3 x i8] c"1C\00", align 1
; CHECK: @_ZTI1C = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1C, ptr @_ZTI1B }, align 8
;.
define internal noundef ptr @_Z4testP1A(ptr noundef %a) {
; CHECK-LABEL: define internal noundef ptr @_Z4testP1A(
; CHECK-SAME: ptr noundef [[A:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
; CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[TMP0]], null
; CHECK-NEXT:    br i1 [[TMP1]], label %[[DYNAMIC_CAST_NULL:.*]], label %[[LOAD_BLOCK:.*]]
; CHECK:       [[LOAD_BLOCK]]:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[TMP0]], align 8
; CHECK-NEXT:    br label %[[CHECK_POINT_0:.*]]
; CHECK:       [[CHECK_POINT_0]]:
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1B, i64 16)
; CHECK-NEXT:    br i1 [[TMP2]], label %[[HANDLE_OFFSET:.*]], label %[[CHECK_POINT_1:.*]]
; CHECK:       [[CHECK_POINT_1]]:
; CHECK-NEXT:    [[TMP3:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1E, i64 16)
; CHECK-NEXT:    br i1 [[TMP3]], label %[[HANDLE_OFFSET]], label %[[CHECK_POINT_2:.*]]
; CHECK:       [[CHECK_POINT_2]]:
; CHECK-NEXT:    [[TMP4:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1D, i64 40)
; CHECK-NEXT:    br i1 [[TMP4]], label %[[HANDLE_OFFSET]], label %[[CHECK_POINT_3:.*]]
; CHECK:       [[CHECK_POINT_3]]:
; CHECK-NEXT:    [[TMP5:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1C, i64 16)
; CHECK-NEXT:    br i1 [[TMP5]], label %[[HANDLE_OFFSET]], label %[[DYNAMIC_CAST_NOTNULL:.*]]
; CHECK:       [[HANDLE_OFFSET]]:
; CHECK-NEXT:    br label %[[DYNAMIC_CAST_NOTNULL]]
; CHECK:       [[DYNAMIC_CAST_NOTNULL]]:
; CHECK-NEXT:    [[TMP6:%.*]] = phi ptr [ null, %[[CHECK_POINT_3]] ], [ [[TMP0]], %[[HANDLE_OFFSET]] ]
; CHECK-NEXT:    br label %[[DYNAMIC_CAST_END:.*]]
; CHECK:       [[DYNAMIC_CAST_NULL]]:
; CHECK-NEXT:    br label %[[DYNAMIC_CAST_END]]
; CHECK:       [[DYNAMIC_CAST_END]]:
; CHECK-NEXT:    [[TMP7:%.*]] = phi ptr [ [[TMP6]], %[[DYNAMIC_CAST_NOTNULL]] ], [ null, %[[DYNAMIC_CAST_NULL]] ]
; CHECK-NEXT:    ret ptr [[TMP7]]
;
entry:
  %a.addr = alloca ptr, align 8
  store ptr %a, ptr %a.addr, align 8
  %0 = load ptr, ptr %a.addr, align 8
  %1 = icmp eq ptr %0, null
  br i1 %1, label %dynamic_cast.null, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %2 = call ptr @__dynamic_cast(ptr %0, ptr @_ZTI1A, ptr @_ZTI1B, i64 0)
  br label %dynamic_cast.end

dynamic_cast.null:                                ; preds = %entry
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %dynamic_cast.null, %dynamic_cast.notnull
  %3 = phi ptr [ %2, %dynamic_cast.notnull ], [ null, %dynamic_cast.null ]
  ret ptr %3
}

declare ptr @__dynamic_cast(ptr, ptr, ptr, i64)

define internal noundef i32 @main() {
; CHECK-LABEL: define internal noundef i32 @main() {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[RETVAL:%.*]] = alloca i32, align 4
; CHECK-NEXT:    [[B:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store i32 0, ptr [[RETVAL]], align 4
; CHECK-NEXT:    [[CALL:%.*]] = call noalias noundef nonnull ptr @_Znwm(i64 noundef 32)
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[CALL]], i8 0, i64 32, i1 false)
; CHECK-NEXT:    call void @_ZN1DC2Ev(ptr noundef nonnull align 8 dereferenceable(28) [[CALL]])
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[CALL]], null
; CHECK-NEXT:    br i1 [[TMP0]], label %[[CAST_END:.*]], label %[[CAST_NOTNULL:.*]]
; CHECK:       [[CAST_NOTNULL]]:
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[CALL]], i64 16
; CHECK-NEXT:    br label %[[CAST_END]]
; CHECK:       [[CAST_END]]:
; CHECK-NEXT:    [[CAST_RESULT:%.*]] = phi ptr [ [[ADD_PTR]], %[[CAST_NOTNULL]] ], [ null, %[[ENTRY]] ]
; CHECK-NEXT:    [[CALL1:%.*]] = call noundef ptr @_Z4testP1A(ptr noundef [[CAST_RESULT]])
; CHECK-NEXT:    [[CALL2:%.*]] = call noalias noundef nonnull ptr @_Znwm(i64 noundef 16)
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[CALL2]], i8 0, i64 16, i1 false)
; CHECK-NEXT:    call void @_ZN1EC2Ev(ptr noundef nonnull align 8 dereferenceable(12) [[CALL2]])
; CHECK-NEXT:    [[CALL3:%.*]] = call noundef ptr @_Z4testP1A(ptr noundef [[CALL2]])
; CHECK-NEXT:    [[CALL4:%.*]] = call noalias noundef nonnull ptr @_Znwm(i64 noundef 16)
; CHECK-NEXT:    call void @llvm.memset.p0.i64(ptr align 16 [[CALL4]], i8 0, i64 16, i1 false)
; CHECK-NEXT:    call void @_ZN1CC2Ev(ptr noundef nonnull align 8 dereferenceable(12) [[CALL4]])
; CHECK-NEXT:    [[CALL5:%.*]] = call noundef ptr @_Z4testP1A(ptr noundef [[CALL4]])
; CHECK-NEXT:    store ptr [[CALL5]], ptr [[B]], align 8
; CHECK-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[B]], align 8
; CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP1]], align 8
; CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTS1A")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP2]])
; CHECK-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 0
; CHECK-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[VFN]], align 8
; CHECK-NEXT:    call void [[TMP3]](ptr noundef nonnull align 8 dereferenceable(12) [[TMP1]])
; CHECK-NEXT:    [[TMP4:%.*]] = load i32, ptr [[RETVAL]], align 4
; CHECK-NEXT:    ret i32 [[TMP4]]
;
entry:
  %retval = alloca i32, align 4
  %b = alloca ptr, align 8
  store i32 0, ptr %retval, align 4
  %call = call noalias noundef nonnull ptr @_Znwm(i64 noundef 32)
  call void @llvm.memset.p0.i64(ptr align 16 %call, i8 0, i64 32, i1 false)
  call void @_ZN1DC2Ev(ptr noundef nonnull align 8 dereferenceable(28) %call)
  %0 = icmp eq ptr %call, null
  br i1 %0, label %cast.end, label %cast.notnull

cast.notnull:                                     ; preds = %entry
  %add.ptr = getelementptr inbounds i8, ptr %call, i64 16
  br label %cast.end

cast.end:                                         ; preds = %cast.notnull, %entry
  %cast.result = phi ptr [ %add.ptr, %cast.notnull ], [ null, %entry ]
  %call1 = call noundef ptr @_Z4testP1A(ptr noundef %cast.result)
  %call2 = call noalias noundef nonnull ptr @_Znwm(i64 noundef 16)
  call void @llvm.memset.p0.i64(ptr align 16 %call2, i8 0, i64 16, i1 false)
  call void @_ZN1EC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %call2)
  %call3 = call noundef ptr @_Z4testP1A(ptr noundef %call2)
  %call4 = call noalias noundef nonnull ptr @_Znwm(i64 noundef 16)
  call void @llvm.memset.p0.i64(ptr align 16 %call4, i8 0, i64 16, i1 false)
  call void @_ZN1CC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %call4)
  %call5 = call noundef ptr @_Z4testP1A(ptr noundef %call4)
  store ptr %call5, ptr %b, align 8
  %1 = load ptr, ptr %b, align 8
  %vtable = load ptr, ptr %1, align 8
  %2 = call i1 @llvm.type.test(ptr %vtable, metadata !"_ZTS1A")
  call void @llvm.assume(i1 %2)
  %vfn = getelementptr inbounds ptr, ptr %vtable, i64 0
  %3 = load ptr, ptr %vfn, align 8
  call void %3(ptr noundef nonnull align 8 dereferenceable(12) %1)
  %4 = load i32, ptr %retval, align 4
  ret i32 %4
}

declare noundef nonnull ptr @_Znwm(i64 noundef)

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: write)
declare void @llvm.memset.p0.i64(ptr nocapture writeonly, i8, i64, i1 immarg) #0

define internal void @_ZN1DC2Ev(ptr noundef nonnull align 8 dereferenceable(28) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN1DC2Ev(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(28) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    call void @_ZN2AAC2Ev(ptr noundef nonnull align 8 dereferenceable(12) [[THIS1]])
; CHECK-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i64 16
; CHECK-NEXT:    call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(12) [[TMP0]])
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr], [3 x ptr] }, ptr @_ZTV1D, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i64 16
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr], [3 x ptr] }, ptr @_ZTV1D, i32 0, i32 1, i32 2), ptr [[ADD_PTR]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  call void @_ZN2AAC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this1)
  %0 = getelementptr inbounds i8, ptr %this1, i64 16
  call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %0)
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr], [3 x ptr] }, ptr @_ZTV1D, i32 0, i32 0, i32 2), ptr %this1, align 8
  %add.ptr = getelementptr inbounds i8, ptr %this1, i64 16
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr], [3 x ptr] }, ptr @_ZTV1D, i32 0, i32 1, i32 2), ptr %add.ptr, align 8
  ret void
}

define internal void @_ZN1EC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN1EC2Ev(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(12) [[THIS1]])
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1E, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this1)
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1E, i32 0, i32 0, i32 2), ptr %this1, align 8
  ret void
}

define internal void @_ZN1CC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN1CC2Ev(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(12) [[THIS1]])
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1C, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this1)
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1C, i32 0, i32 0, i32 2), ptr %this1, align 8
  ret void
}

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare i1 @llvm.type.test(ptr, metadata) #1

; Function Attrs: nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write)
declare void @llvm.assume(i1 noundef) #2

define internal void @_ZN2AAC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN2AAC2Ev(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV2AA, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV2AA, i32 0, i32 0, i32 2), ptr %this1, align 8
  ret void
}

define internal void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN1BC2Ev(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(12) [[THIS1]])
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1B, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this1)
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1B, i32 0, i32 0, i32 2), ptr %this1, align 8
  ret void
}

define internal void @_ZN2AA3barEv(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN2AA3barEv(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  ret void
}

define internal void @_ZN1A3fooEv(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN1A3fooEv(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  ret void
}

define internal void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN1AC2Ev(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
; CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
; CHECK-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1A, i32 0, i32 0, i32 2), ptr [[THIS1]], align 8
; CHECK-NEXT:    ret void
;
entry:
  %this.addr = alloca ptr, align 8
  store ptr %this, ptr %this.addr, align 8
  %this1 = load ptr, ptr %this.addr, align 8
  store ptr getelementptr inbounds inrange(-16, 8) ({ [3 x ptr] }, ptr @_ZTV1A, i32 0, i32 0, i32 2), ptr %this1, align 8
  ret void
}

attributes #0 = { nocallback nofree nounwind willreturn memory(argmem: write) }
attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
attributes #2 = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }

!0 = !{i64 40, !"_ZTS1A"}
!1 = !{i64 16, !"_ZTSM1AFvvE.virtual"}
!2 = !{i64 40, !"_ZTSM1AFvvE.virtual"}
!3 = !{i64 40, !"_ZTS1B"}
!4 = !{i64 16, !"_ZTSM1BFvvE.virtual"}
!5 = !{i64 40, !"_ZTSM1BFvvE.virtual"}
!6 = !{i64 16, !"_ZTS1D"}
!7 = !{i64 16, !"_ZTSM1DFvvE.virtual"}
!8 = !{i64 40, !"_ZTSM1DFvvE.virtual"}
!9 = !{i64 16, !"_ZTS2AA"}
!10 = !{i64 16, !"_ZTSM2AAFvvE.virtual"}
!11 = !{i64 40, !"_ZTSM2AAFvvE.virtual"}
!12 = !{i64 1}
!13 = !{i64 16, !"_ZTS1A"}
!14 = !{i64 16, !"_ZTS1B"}
!15 = !{i64 16, !"_ZTS1E"}
!16 = !{i64 16, !"_ZTSM1EFvvE.virtual"}
!17 = !{i64 16, !"_ZTS1C"}
!18 = !{i64 16, !"_ZTSM1CFvvE.virtual"}
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nounwind willreturn memory(argmem: write) }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR2:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
;.
; CHECK: [[META0]] = !{i64 40, !"_ZTS1A"}
; CHECK: [[META1]] = !{i64 16, !"_ZTSM1AFvvE.virtual"}
; CHECK: [[META2]] = !{i64 40, !"_ZTSM1AFvvE.virtual"}
; CHECK: [[META3]] = !{i64 40, !"_ZTS1B"}
; CHECK: [[META4]] = !{i64 16, !"_ZTSM1BFvvE.virtual"}
; CHECK: [[META5]] = !{i64 40, !"_ZTSM1BFvvE.virtual"}
; CHECK: [[META6]] = !{i64 16, !"_ZTS1D"}
; CHECK: [[META7]] = !{i64 16, !"_ZTSM1DFvvE.virtual"}
; CHECK: [[META8]] = !{i64 40, !"_ZTSM1DFvvE.virtual"}
; CHECK: [[META9]] = !{i64 16, !"_ZTS2AA"}
; CHECK: [[META10]] = !{i64 16, !"_ZTSM2AAFvvE.virtual"}
; CHECK: [[META11]] = !{i64 40, !"_ZTSM2AAFvvE.virtual"}
; CHECK: [[META12]] = !{i64 1}
; CHECK: [[META13]] = !{i64 16, !"_ZTS1A"}
; CHECK: [[META14]] = !{i64 16, !"_ZTS1B"}
; CHECK: [[META15]] = !{i64 16, !"_ZTS1E"}
; CHECK: [[META16]] = !{i64 16, !"_ZTSM1EFvvE.virtual"}
; CHECK: [[META17]] = !{i64 16, !"_ZTS1C"}
; CHECK: [[META18]] = !{i64 16, !"_ZTSM1CFvvE.virtual"}
;.
