; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 4
; RUN: opt -S -passes=dyncastopt -enable-negative-test=false < %s | FileCheck %s
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

@_ZTI1B = linkonce_odr hidden constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null }, align 8
@_ZTI1A = linkonce_odr hidden constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null }, align 8
@_ZTI1C = linkonce_odr hidden constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, i32 0, i32 2, ptr @_ZTI1A, i64 2, ptr @_ZTI1B, i64 2050 }, align 8
@_ZTV1D = linkonce_odr hidden constant { [4 x ptr], [4 x ptr], [3 x ptr] } { [4 x ptr] [ptr null, ptr @_ZTI1D, ptr null, ptr null], [4 x ptr] [ptr inttoptr (i64 -8 to ptr), ptr @_ZTI1D, ptr null, ptr null], [3 x ptr] [ptr inttoptr (i64 -16 to ptr), ptr @_ZTI1D, ptr null] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !4, !type !5, !type !6, !type !7, !type !8, !type !9, !type !10, !type !11, !type !12, !type !13, !type !14, !type !15, !type !16, !type !17, !type !18, !type !19, !type !20, !type !21, !type !22, !type !23, !type !24, !type !25, !type !26, !type !27, !type !28, !type !29, !vcall_visibility !30
@_ZTI2AA = linkonce_odr hidden constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null }, align 8
@_ZTI1D = linkonce_odr hidden constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr null, i64 2), ptr null, i32 0, i32 2, ptr @_ZTI2AA, i64 2, ptr @_ZTI1C, i64 2050 }, align 8

define hidden ptr @_Z4testP1B(ptr %b) {
; CHECK-LABEL: define hidden ptr @_Z4testP1B(
; CHECK-SAME: ptr [[B:%.*]]) {
; CHECK-NEXT:  entry:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[B]], null
; CHECK-NEXT:    br i1 [[TMP0]], label [[DYNAMIC_CAST_END:%.*]], label [[LOAD_BLOCK:%.*]]
; CHECK:       load_block:
; CHECK-NEXT:    [[VPTR:%.*]] = load ptr, ptr [[B]], align 8
; CHECK-NEXT:    [[TMP6:%.*]] = call i1 @llvm.type.test(ptr [[VPTR]], metadata !"_ZTS1B")
; CHECK-NEXT:    call void @llvm.assume(i1 [[TMP6]])
; CHECK-NEXT:    [[ADD_OFFSET_TO_TOP:%.*]] = getelementptr inbounds i8, ptr [[VPTR]], i64 -16
; CHECK-NEXT:    [[OFFSET_TO_TOP:%.*]] = load i64, ptr [[ADD_OFFSET_TO_TOP]], align 8
; CHECK-NEXT:    [[RUNTIME_OBJECT:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 [[OFFSET_TO_TOP]]
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[RUNTIME_OBJECT]], align 8
; CHECK-NEXT:    br label [[CHECK_POINT_0:%.*]]
; CHECK:       check_point.0:
; CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1D, i64 16)
; CHECK-NEXT:    br i1 [[TMP1]], label [[HANDLE_OFFSET:%.*]], label [[DYNAMIC_CAST_NOTNULL:%.*]]
; CHECK:       handle_offset:
; CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i8, ptr [[B]], i64 -8
; CHECK-NEXT:    br label [[DYNAMIC_CAST_NOTNULL]]
; CHECK:       dynamic_cast.notnull:
; CHECK-NEXT:    [[TMP4:%.*]] = phi ptr [ null, [[CHECK_POINT_0]] ], [ [[TMP3]], [[HANDLE_OFFSET]] ]
; CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
; CHECK:       dynamic_cast.end:
; CHECK-NEXT:    [[TMP5:%.*]] = phi ptr [ [[TMP4]], [[DYNAMIC_CAST_NOTNULL]] ], [ null, [[ENTRY:%.*]] ]
; CHECK-NEXT:    ret ptr [[TMP5]]
;
entry:
  %0 = icmp eq ptr %b, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %b, ptr nonnull @_ZTI1B, ptr nonnull @_ZTI1C, i64 8)
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %dynamic_cast.notnull, %entry
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

; Function Attrs: nofree nounwind memory(read)
declare ptr @__dynamic_cast(ptr, ptr, ptr, i64)

!0 = !{i64 48, !"_ZTS1A"}
!1 = !{i64 16, !"_ZTSM1AFivE.virtual"}
!2 = !{i64 24, !"_ZTSM1AFivE.virtual"}
!3 = !{i64 48, !"_ZTSM1AFivE.virtual"}
!4 = !{i64 56, !"_ZTSM1AFivE.virtual"}
!5 = !{i64 80, !"_ZTSM1AFivE.virtual"}
!6 = !{i64 80, !"_ZTS1B"}
!7 = !{i64 16, !"_ZTSM1BFivE.virtual"}
!8 = !{i64 24, !"_ZTSM1BFivE.virtual"}
!9 = !{i64 48, !"_ZTSM1BFivE.virtual"}
!10 = !{i64 56, !"_ZTSM1BFivE.virtual"}
!11 = !{i64 80, !"_ZTSM1BFivE.virtual"}
!12 = !{i64 48, !"_ZTS1C"}
!13 = !{i64 16, !"_ZTSM1CFivE.virtual"}
!14 = !{i64 24, !"_ZTSM1CFivE.virtual"}
!15 = !{i64 48, !"_ZTSM1CFivE.virtual"}
!16 = !{i64 56, !"_ZTSM1CFivE.virtual"}
!17 = !{i64 80, !"_ZTSM1CFivE.virtual"}
!18 = !{i64 16, !"_ZTS1D"}
!19 = !{i64 16, !"_ZTSM1DFivE.virtual"}
!20 = !{i64 24, !"_ZTSM1DFivE.virtual"}
!21 = !{i64 48, !"_ZTSM1DFivE.virtual"}
!22 = !{i64 56, !"_ZTSM1DFivE.virtual"}
!23 = !{i64 80, !"_ZTSM1DFivE.virtual"}
!24 = !{i64 16, !"_ZTS2AA"}
!25 = !{i64 16, !"_ZTSM2AAFivE.virtual"}
!26 = !{i64 24, !"_ZTSM2AAFivE.virtual"}
!27 = !{i64 48, !"_ZTSM2AAFivE.virtual"}
!28 = !{i64 56, !"_ZTSM2AAFivE.virtual"}
!29 = !{i64 80, !"_ZTSM2AAFivE.virtual"}
!30 = !{i64 1}
