; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt -passes=dyncastopt -enable-negative-test=false -S < %s | FileCheck %s

target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128-Fn32"
target triple = "aarch64-unknown-linux-gnu"

@_ZTVN10__cxxabiv117__class_type_infoE = external global [0 x ptr]
@_ZTS1A = internal constant [3 x i8] c"1A\00", align 1
@_ZTI1A = internal constant { ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv117__class_type_infoE, i64 2), ptr @_ZTS1A }, align 8
@_ZTVN10__cxxabiv120__si_class_type_infoE = external global [0 x ptr]
@_ZTS1E = internal constant [3 x i8] c"1E\00", align 1
@_ZTI1E = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1E, ptr @_ZTI1A }, align 8
@_ZTV1D = internal unnamed_addr constant { [4 x ptr], [4 x ptr] } { [4 x ptr] [ptr inttoptr (i64 16 to ptr), ptr null, ptr @_ZTI1D, ptr @_ZN1A3fooEv], [4 x ptr] [ptr null, ptr inttoptr (i64 -16 to ptr), ptr @_ZTI1D, ptr @_ZN1A3fooEv] }, align 8, !type !0, !type !1, !type !2, !type !3, !type !1, !type !2, !type !4, !type !5, !type !6, !type !7, !type !8, !type !9, !type !10, !type !11, !type !12, !vcall_visibility !13, !virtual_inheritance !14
@_ZTVN10__cxxabiv121__vmi_class_type_infoE = external global [0 x ptr]
@_ZTS1D = internal constant [3 x i8] c"1D\00", align 1
@_ZTS1B = internal constant [3 x i8] c"1B\00", align 1
@_ZTI1B = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1B, ptr @_ZTI1A }, align 8
@_ZTS1C = internal constant [3 x i8] c"1C\00", align 1
@_ZTI1C = internal constant { ptr, ptr, ptr } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv120__si_class_type_infoE, i64 2), ptr @_ZTS1C, ptr @_ZTI1A }, align 8
@_ZTI1D = internal constant { ptr, ptr, i32, i32, ptr, i64, ptr, i64 } { ptr getelementptr inbounds (ptr, ptr @_ZTVN10__cxxabiv121__vmi_class_type_infoE, i64 2), ptr @_ZTS1D, i32 1, i32 2, ptr @_ZTI1B, i64 -6141, ptr @_ZTI1C, i64 2 }, align 8
@_ZTV1E = internal unnamed_addr constant { [3 x ptr] } { [3 x ptr] [ptr null, ptr @_ZTI1E, ptr @_ZN1A3fooEv] }, align 8, !type !15, !type !16, !type !17, !type !18, !vcall_visibility !13

define internal noundef ptr @_Z5test1P1A(ptr noundef readonly %a) local_unnamed_addr {
; CHECK-LABEL: define internal noundef ptr @_Z5test1P1A(
; CHECK-SAME: ptr noundef readonly [[A:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label %[[DYNAMIC_CAST_END:.*]], label %[[LOAD_BLOCK:.*]]
; CHECK:       [[LOAD_BLOCK]]:
; CHECK-NEXT:    [[RUNTIME_VPTR:%.*]] = load ptr, ptr [[A]], align 8
; CHECK-NEXT:    br label %[[CHECK_POINT_0:.*]]
; CHECK:       [[CHECK_POINT_0]]:
; CHECK-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[RUNTIME_VPTR]], getelementptr inbounds (i8, ptr @_ZTV1E, i64 16)
; CHECK-NEXT:    br i1 [[TMP2]], label %[[HANDLE_OFFSET:.*]], label %[[DYNAMIC_CAST_NOTNULL:.*]]
; CHECK:       [[HANDLE_OFFSET]]:
; CHECK-NEXT:    br label %[[DYNAMIC_CAST_NOTNULL]]
; CHECK:       [[DYNAMIC_CAST_NOTNULL]]:
; CHECK-NEXT:    [[TMP3:%.*]] = phi ptr [ null, %[[CHECK_POINT_0]] ], [ [[A]], %[[HANDLE_OFFSET]] ]
; CHECK-NEXT:    br label %[[DYNAMIC_CAST_END]]
; CHECK:       [[DYNAMIC_CAST_END]]:
; CHECK-NEXT:    [[TMP5:%.*]] = phi ptr [ [[TMP3]], %[[DYNAMIC_CAST_NOTNULL]] ], [ null, %[[ENTRY]] ]
; CHECK-NEXT:    ret ptr [[TMP5]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1E, i64 0)
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %dynamic_cast.notnull, %entry
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

; Function Attrs: mustprogress nofree nounwind willreturn memory(read) uwtable
define hidden noundef ptr @_Z5test3P1A(ptr noundef readonly %a) local_unnamed_addr #3 {
; CHECK-LABEL: define hidden noundef ptr @_Z5test3P1A(
; CHECK-SAME: ptr noundef readonly [[A:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label %[[DYNAMIC_CAST_END:.*]], label %[[DYNAMIC_CAST_NOTNULL:.*]]
; CHECK:       [[DYNAMIC_CAST_NOTNULL]]:
; CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr @__dynamic_cast(ptr nonnull [[A]], ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1D, i64 -1)
; CHECK-NEXT:    br label %[[DYNAMIC_CAST_END]]
; CHECK:       [[DYNAMIC_CAST_END]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi ptr [ [[TMP1]], %[[DYNAMIC_CAST_NOTNULL]] ], [ null, %[[ENTRY]] ]
; CHECK-NEXT:    ret ptr [[TMP2]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1D, i64 -1) #7
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %entry, %dynamic_cast.notnull
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

; Function Attrs: mustprogress nofree nounwind willreturn memory(read) uwtable
define hidden noundef ptr @_Z5test4P1A(ptr noundef readonly %a) local_unnamed_addr #3 {
; CHECK-LABEL: define hidden noundef ptr @_Z5test4P1A(
; CHECK-SAME: ptr noundef readonly [[A:%.*]]) local_unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*]]:
; CHECK-NEXT:    [[TMP0:%.*]] = icmp eq ptr [[A]], null
; CHECK-NEXT:    br i1 [[TMP0]], label %[[DYNAMIC_CAST_END:.*]], label %[[DYNAMIC_CAST_NOTNULL:.*]]
; CHECK:       [[DYNAMIC_CAST_NOTNULL]]:
; CHECK-NEXT:    [[TMP1:%.*]] = tail call ptr @__dynamic_cast(ptr nonnull [[A]], ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1B, i64 0)
; CHECK-NEXT:    br label %[[DYNAMIC_CAST_END]]
; CHECK:       [[DYNAMIC_CAST_END]]:
; CHECK-NEXT:    [[TMP2:%.*]] = phi ptr [ [[TMP1]], %[[DYNAMIC_CAST_NOTNULL]] ], [ null, %[[ENTRY]] ]
; CHECK-NEXT:    ret ptr [[TMP2]]
;
entry:
  %0 = icmp eq ptr %a, null
  br i1 %0, label %dynamic_cast.end, label %dynamic_cast.notnull

dynamic_cast.notnull:                             ; preds = %entry
  %1 = tail call ptr @__dynamic_cast(ptr nonnull %a, ptr nonnull @_ZTI1A, ptr nonnull @_ZTI1B, i64 0) #7
  br label %dynamic_cast.end

dynamic_cast.end:                                 ; preds = %entry, %dynamic_cast.notnull
  %2 = phi ptr [ %1, %dynamic_cast.notnull ], [ null, %entry ]
  ret ptr %2
}

declare ptr @__dynamic_cast(ptr, ptr, ptr, i64) local_unnamed_addr

define internal void @_ZN1A3fooEv(ptr noundef nonnull align 8 dereferenceable(12) %this) unnamed_addr {
; CHECK-LABEL: define internal void @_ZN1A3fooEv(
; CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(12) [[THIS:%.*]]) unnamed_addr {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    ret void
;
entry:
  ret void
}

!0 = !{i64 24, !"_ZTS1A"}
!1 = !{i64 24, !"_ZTSM1AFvvE.virtual"}
!2 = !{i64 56, !"_ZTSM1AFvvE.virtual"}
!3 = !{i64 56, !"_ZTS1A"}
!4 = !{i64 56, !"_ZTS1B"}
!5 = !{i64 24, !"_ZTSM1BFvvE.virtual"}
!6 = !{i64 56, !"_ZTSM1BFvvE.virtual"}
!7 = !{i64 24, !"_ZTS1C"}
!8 = !{i64 24, !"_ZTSM1CFvvE.virtual"}
!9 = !{i64 56, !"_ZTSM1CFvvE.virtual"}
!10 = !{i64 24, !"_ZTS1D"}
!11 = !{i64 24, !"_ZTSM1DFvvE.virtual"}
!12 = !{i64 56, !"_ZTSM1DFvvE.virtual"}
!13 = !{i64 1}
!14 = !{}
!15 = !{i64 16, !"_ZTS1A"}
!16 = !{i64 16, !"_ZTSM1AFvvE.virtual"}
!17 = !{i64 16, !"_ZTS1E"}
!18 = !{i64 16, !"_ZTSM1EFvvE.virtual"}
