; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 4
; RUN: opt < %s -passes=rtti-clean -S | FileCheck %s
target datalayout = "e-p:64:64"
target triple = "aarch64-unknown-linux-gnu"

declare i1 @llvm.type.test(ptr, metadata)
declare void @llvm.assume(i1)
declare ptr @__dynamic_cast(ptr, ptr, ptr, i64)
declare void @__cxa_throw(ptr, ptr, ptr)

%vtTy = type { [3 x ptr] }

declare i32 @vf()

@_ZTIvt = internal constant %vtTy zeroinitializer
@_ZTIvt1 = internal constant %vtTy zeroinitializer
@_ZTIvt2 = internal constant %vtTy zeroinitializer
@_ZTIvt4 = internal constant %vtTy zeroinitializer

; Check _ZTVvt is optimized which the first two vtable slots are eliminated.
@_ZTVvt = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0

; Check _ZTVvt1 is not optimized since there is rtti load site.
@_ZTVvt1 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !1

; Check _ZTVvt2 is not optimized since there is dynamic cast for this type.
@_ZTVvt2 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !2

; TODO: support virtual inheritance
; Check _ZTVvt3 is not optimized since it has virtual inheritance metadata.
@_ZTVvt3 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !3, !virtual_inheritance !4

; Check _ZTVvt4 is not optimized since there is a throw site.
@_ZTVvt4 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !5

; Check vcall_visibility also works.
@_ZTVvt5 = constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !7, !vcall_visibility !6

; Check the optimization for _ZTVvt also adjust the offset in constants.
@temp = internal constant ptr getelementptr inbounds (%vtTy, ptr @_ZTVvt, i32 0, i32 0, i32 2)

; FIXME: although there is a reference to _ZTVvt, we still optimize for it.
; This may have some potential problems.
@nongepuse = internal constant [ 2 x ptr ] [ ptr null, ptr @_ZTVvt ]

; TODO: support reduce vtable slot for merged vtables
; Check that merged vtables are skipped.
@_ZTV.merged = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0

; FIXME: Optimize weak_odr is not correct.
@_ZTVvt6 = weak_odr constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !8


;.
; CHECK: @_ZTIvt = internal constant %vtTy zeroinitializer
; CHECK: @_ZTIvt1 = internal constant %vtTy zeroinitializer
; CHECK: @_ZTIvt2 = internal constant %vtTy zeroinitializer
; CHECK: @_ZTIvt4 = internal constant %vtTy zeroinitializer
; CHECK: @_ZTVvt = internal constant { [1 x ptr] } { [1 x ptr] [ptr @vf] }, !type [[META0:![0-9]+]]
; CHECK: @_ZTVvt1 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META1:![0-9]+]]
; CHECK: @_ZTVvt2 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META2:![0-9]+]]
; CHECK: @_ZTVvt3 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META3:![0-9]+]], !virtual_inheritance [[META4:![0-9]+]]
; CHECK: @_ZTVvt4 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META5:![0-9]+]]
; CHECK: @_ZTVvt5 = constant { [1 x ptr] } { [1 x ptr] [ptr @vf] }, !type [[META6:![0-9]+]], !vcall_visibility [[META7:![0-9]+]]
; CHECK: @temp = internal constant ptr @_ZTVvt
; CHECK: @nongepuse = internal constant [2 x ptr] [ptr null, ptr @_ZTVvt]
; CHECK: @_ZTV.merged = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META8:![0-9]+]]
; CHECK: @_ZTVvt6 = weak_odr constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META9:![0-9]+]]
;.
define i32 @vcall(ptr %p) {
; CHECK-LABEL: define i32 @vcall(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTSvt")
; CHECK-NEXT:    call void @llvm.assume(i1 [[T]])
; CHECK-NEXT:    [[FPTR:%.*]] = load ptr, ptr [[VTABLE]], align 8
; CHECK-NEXT:    [[RESULT:%.*]] = call i32 [[FPTR]]()
; CHECK-NEXT:    ret i32 [[RESULT]]
;
  %vtable = load ptr, ptr %p
  %t = call i1 @llvm.type.test(ptr %vtable, metadata !"_ZTSvt")
  call void @llvm.assume(i1 %t)
  %fptr = load ptr, ptr %vtable
  %result = call i32 %fptr()
  ret i32 %result
}

define ptr @rtti_load(ptr %p) {
; CHECK-LABEL: define ptr @rtti_load(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[P]], align 8
; CHECK-NEXT:    [[T:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTSvt1")
; CHECK-NEXT:    call void @llvm.assume(i1 [[T]])
; CHECK-NEXT:    [[AP:%.*]] = getelementptr inbounds i8, ptr [[VTABLE]], i64 -8
; CHECK-NEXT:    [[RTTI:%.*]] = load ptr, ptr [[AP]], align 8
; CHECK-NEXT:    ret ptr [[RTTI]]
;
  %vtable = load ptr, ptr %p
  %t = call i1 @llvm.type.test(ptr %vtable, metadata !"_ZTSvt1")
  call void @llvm.assume(i1 %t)
  %ap = getelementptr inbounds i8, ptr %vtable, i64 -8
  %rtti = load ptr, ptr %ap
  ret ptr %rtti
}

define ptr @dyncast(ptr %a) {
; CHECK-LABEL: define ptr @dyncast(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:    [[B:%.*]] = call ptr @__dynamic_cast(ptr [[A]], ptr @_ZTIvt2, ptr @_ZTIvt2, i64 0)
; CHECK-NEXT:    ret ptr [[B]]
;
  %b = call ptr @__dynamic_cast(ptr %a, ptr @_ZTIvt2, ptr @_ZTIvt2, i64 0)
  ret ptr %b
}

define void @eh(ptr %a) {
; CHECK-LABEL: define void @eh(
; CHECK-SAME: ptr [[A:%.*]]) {
; CHECK-NEXT:    call void @__cxa_throw(ptr [[A]], ptr @_ZTIvt4, ptr [[A]])
; CHECK-NEXT:    ret void
;
  call void @__cxa_throw(ptr %a, ptr @_ZTIvt4, ptr %a)
  ret void
}

define void @use(ptr %p) {
; CHECK-LABEL: define void @use(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store ptr @_ZTVvt, ptr [[P]], align 8
; CHECK-NEXT:    store ptr @_ZTVvt, ptr [[P]], align 8
; CHECK-NEXT:    store ptr getelementptr inbounds ([[VTTY:%.*]], ptr @_ZTVvt1, i32 0, i32 0, i32 2), ptr [[P]], align 8
; CHECK-NEXT:    store ptr getelementptr inbounds ([[VTTY]], ptr @_ZTVvt2, i32 0, i32 0, i32 2), ptr [[P]], align 8
; CHECK-NEXT:    ret void
;
  store ptr getelementptr inbounds ( %vtTy, ptr @_ZTVvt, i32 0, i32 0, i32 2), ptr %p
  store ptr getelementptr inbounds (i8, ptr @_ZTVvt, i64 16),  ptr %p
  store ptr getelementptr inbounds ( %vtTy, ptr @_ZTVvt1, i32 0, i32 0, i32 2), ptr %p
  store ptr getelementptr inbounds ( %vtTy, ptr @_ZTVvt2, i32 0, i32 0, i32 2), ptr %p
  ret void
}

!0 = !{i32 16, !"_ZTSvt"}
!1 = !{i32 16, !"_ZTSvt1"}
!2 = !{i32 16, !"_ZTSvt2"}
!3 = !{i32 16, !"_ZTSvt3"}
!4 = !{}
!5 = !{i32 16, !"_ZTSvt4"}
!6 = !{i64 1}
!7 = !{i32 16, !"_ZTSvt5"}
!8 = !{i32 16, !"_ZTSvt6"}
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
;.
; CHECK: [[META0]] = !{i64 0, !"_ZTSvt"}
; CHECK: [[META1]] = !{i32 16, !"_ZTSvt1"}
; CHECK: [[META2]] = !{i32 16, !"_ZTSvt2"}
; CHECK: [[META3]] = !{i32 16, !"_ZTSvt3"}
; CHECK: [[META4]] = !{}
; CHECK: [[META5]] = !{i32 16, !"_ZTSvt4"}
; CHECK: [[META6]] = !{i64 0, !"_ZTSvt5"}
; CHECK: [[META7]] = !{i64 1}
; CHECK: [[META8]] = !{i32 16, !"_ZTSvt"}
; CHECK: [[META9]] = !{i32 16, !"_ZTSvt6"}
;.
