; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 4
; RUN: opt < %s -passes=rtti-clean -S | FileCheck %s
target datalayout = "e-p:64:64"
target triple = "aarch64-unknown-linux-gnu"

%vtTy = type { [3 x ptr], [3 x ptr] }

declare i32 @vf()
@_ZTVvt = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf], [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0, !type !1

;.
; CHECK: @_ZTVvt = internal constant { [1 x ptr], [1 x ptr] } { [1 x ptr] [ptr @vf], [1 x ptr] [ptr @vf] }, !type [[META0:![0-9]+]], !type [[META1:![0-9]+]]
;.
define void @use(ptr %p) {
; CHECK-LABEL: define void @use(
; CHECK-SAME: ptr [[P:%.*]]) {
; CHECK-NEXT:    store ptr getelementptr inbounds ({ [1 x ptr], [1 x ptr] }, ptr @_ZTVvt, i64 0, i32 1, i64 0), ptr [[P]], align 8
; CHECK-NEXT:    store ptr @_ZTVvt, ptr [[P]], align 8
; CHECK-NEXT:    store ptr getelementptr inbounds ({ [1 x ptr], [1 x ptr] }, ptr @_ZTVvt, i64 0, i32 1, i64 0), ptr [[P]], align 8
; CHECK-NEXT:    store ptr @_ZTVvt, ptr [[P]], align 8
; CHECK-NEXT:    ret void
;
  store ptr getelementptr inbounds ( %vtTy, ptr @_ZTVvt, i32 0, i32 1, i32 2), ptr %p
  store ptr getelementptr inbounds ( %vtTy, ptr @_ZTVvt, i32 0, i32 0, i32 2), ptr %p
  store ptr getelementptr inbounds (i8, ptr @_ZTVvt, i64 40),  ptr %p
  store ptr getelementptr inbounds (i8, ptr @_ZTVvt, i64 16),  ptr %p
  ret void
}

!0 = !{i32 16, !"_ZTSvt"}
!1 = !{i32 40, !"_ZTSvt1"}
;.
; CHECK: [[META0]] = !{i64 0, !"_ZTSvt"}
; CHECK: [[META1]] = !{i64 8, !"_ZTSvt1"}
;.
