; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 4
; RUN: opt < %s -passes=rtti-clean -S | FileCheck %s
target datalayout = "e-p:64:64"
target triple = "aarch64-unknown-linux-gnu"

%vtTy = type { [3 x ptr] }

declare i32 @vf()
; Check _ZTVvt1 is not optimized since its subclass is not closed
@_ZTVvt = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0

@_ZTVvt1 = constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0, !type !1

@_ZTVvt2 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0, !type !2

@_ZTVvt3 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0, !type !2

!0 = !{i64 16, !"_ZTSvt"}
!1 = !{i64 16, !"_ZTSvt1"}
!2 = !{i64 16, !"_ZTSvt2"}
!3 = !{i64 16, !"_ZTSvt3"}

;.
; CHECK: [[META0:![0-9]+]] = !{i64 16, !"_ZTSvt"}
; CHECK: [[META1:![0-9]+]] = !{i64 16, !"_ZTSvt1"}
; CHECK: [[META2:![0-9]+]] = !{i64 0, !"_ZTSvt"}
; CHECK: [[META3:![0-9]+]] = !{i64 0, !"_ZTSvt2"}
;.
;; NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
; CHECK: {{.*}}
