; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --check-globals all --version 4
; RUN: opt -module-summary %S/Inputs/rtti.ll -o %t
; RUN: opt -passes=rtti-clean -rtti-clean-read-export-summary=%t %s -S | FileCheck %s
target datalayout = "e-p:64:64"
target triple = "aarch64-unknown-linux-gnu"
%vtTy = type { [3 x ptr] }

declare i1 @llvm.type.test(ptr, metadata)
declare void @llvm.assume(i1)
declare ptr @__dynamic_cast(ptr, ptr, ptr, i64)
declare void @__cxa_throw(ptr, ptr, ptr)

@_ZTVvt = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0

; Check _ZTVvt1 is not optimized since there is rtti load site.
@_ZTVvt1 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !1

; Check _ZTVvt2 is not optimized since there is dynamic cast for this type.
@_ZTVvt2 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !2

; TODO: support virtual inheritance
; Check _ZTVvt3 is not optimized since it has virtual inheritance metadata.
@_ZTVvt3 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !3, !virtual_inheritance !4

; Check _ZTVvt4 is not optimized since there is a throw site.
@_ZTVvt4 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !5

; Check vcall_visibility also works.
@_ZTVvt5 = constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !7, !vcall_visibility !6

; Check the optimization for _ZTVvt also adjust the offset in constants.
@temp = internal constant ptr getelementptr inbounds (%vtTy, ptr @_ZTVvt, i32 0, i32 0, i32 2)

; FIXME: although there is a reference to _ZTVvt, we still optimize for it.
; This may have some potential problems.
@nongepuse = internal constant [ 2 x ptr ] [ ptr null, ptr @_ZTVvt ]

; TODO: support reduce vtable slot for merged vtables
; Check that merged vtables are skipped.
@_ZTV.merged = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !0

; FIXME: Optimize weak_odr is not correct.
@_ZTVvt6 = weak_odr constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type !8

; FIXME: _ZTVvt2 is optimized since the isGuaranteedToBeOptimized always returns true.
; FIXME: _ZTVvt4 should not be optimized since is used by exception handling.
;.
; CHECK: @_ZTVvt = internal constant { [1 x ptr] } { [1 x ptr] [ptr @vf] }, !type [[META0:![0-9]+]]
; CHECK: @_ZTVvt1 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META1:![0-9]+]]
; CHECK: @_ZTVvt2 = internal constant { [1 x ptr] } { [1 x ptr] [ptr @vf] }, !type [[META2:![0-9]+]]
; CHECK: @_ZTVvt3 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META3:![0-9]+]], !virtual_inheritance [[META4:![0-9]+]]
; CHECK: @_ZTVvt4 = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META5:![0-9]+]]
; CHECK: @_ZTVvt5 = constant { [1 x ptr] } { [1 x ptr] [ptr @vf] }, !type [[META6:![0-9]+]], !vcall_visibility [[META7:![0-9]+]]
; CHECK: @temp = internal constant ptr @_ZTVvt
; CHECK: @nongepuse = internal constant [2 x ptr] [ptr null, ptr @_ZTVvt]
; CHECK: @_ZTV.merged = internal constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META8:![0-9]+]]
; CHECK: @_ZTVvt6 = weak_odr constant %vtTy { [3 x ptr] [ptr null, ptr null, ptr @vf] }, !type [[META9:![0-9]+]]
;.
define i32 @vf() {
; CHECK-LABEL: define i32 @vf() {
; CHECK-NEXT:    ret i32 0
;
  ret i32 0
}

!0 = !{i32 16, !"_ZTSvt"}
!1 = !{i32 16, !"_ZTSvt1"}
!2 = !{i32 16, !"_ZTSvt2"}
!3 = !{i32 16, !"_ZTSvt3"}
!4 = !{}
!5 = !{i32 16, !"_ZTSvt4"}
!6 = !{i64 1}
!7 = !{i32 16, !"_ZTSvt5"}
!8 = !{i32 16, !"_ZTSvt6"}
;.
; CHECK: attributes #[[ATTR0:[0-9]+]] = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
; CHECK: attributes #[[ATTR1:[0-9]+]] = { nocallback nofree nosync nounwind willreturn memory(inaccessiblemem: write) }
;.
; CHECK: [[META0]] = !{i64 0, !"_ZTSvt"}
; CHECK: [[META1]] = !{i32 16, !"_ZTSvt1"}
; CHECK: [[META2]] = !{i64 0, !"_ZTSvt2"}
; CHECK: [[META3]] = !{i32 16, !"_ZTSvt3"}
; CHECK: [[META4]] = !{}
; CHECK: [[META5]] = !{i32 16, !"_ZTSvt4"}
; CHECK: [[META6]] = !{i64 0, !"_ZTSvt5"}
; CHECK: [[META7]] = !{i64 1}
; CHECK: [[META8]] = !{i32 16, !"_ZTSvt"}
; CHECK: [[META9]] = !{i32 16, !"_ZTSvt6"}
;.
