// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// RUN: %clang_cc1 -I%S -triple aarch64-unknown-linux -flto -fwhole-program-vtables -emit-llvm -o - %s | FileCheck %s
//
struct Base { virtual void foo() {} };
struct Derived : Base {};

struct __attribute__ ((visibility("hidden"))) Base2 { virtual void foo() {} };
struct __attribute__ ((visibility("hidden"))) Derived2 : Base2 {};

// TODO: Add llvm.type.test and llvm.public.type.test
// CHECK-LABEL: define dso_local noundef ptr @_Z5test1P4Base(
// CHECK-SAME: ptr noundef [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[TMP0]], null
// CHECK-NEXT:    br i1 [[TMP1]], label [[DYNAMIC_CAST_NULL:%.*]], label [[DYNAMIC_CAST_NOTNULL:%.*]]
// CHECK:       dynamic_cast.notnull:
// CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.public.type.test(ptr [[VTABLE]], metadata !"_ZTS4Base")
// CHECK-NEXT:    call void @llvm.assume(i1 [[TMP2]])
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[VTABLE]], i64 -2
// CHECK-NEXT:    [[OFFSET_TO_TOP:%.*]] = load i64, ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[OFFSET_TO_TOP]]
// CHECK-NEXT:    br label [[DYNAMIC_CAST_END:%.*]]
// CHECK:       dynamic_cast.null:
// CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
// CHECK:       dynamic_cast.end:
// CHECK-NEXT:    [[TMP5:%.*]] = phi ptr [ [[TMP4]], [[DYNAMIC_CAST_NOTNULL]] ], [ null, [[DYNAMIC_CAST_NULL]] ]
// CHECK-NEXT:    ret ptr [[TMP5]]
//
void *test1(Base *b) {
  return dynamic_cast<void *>(b);
}

// CHECK-LABEL: define dso_local noundef ptr @_Z5test2P5Base2(
// CHECK-SAME: ptr noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[TMP0]], null
// CHECK-NEXT:    br i1 [[TMP1]], label [[DYNAMIC_CAST_NULL:%.*]], label [[DYNAMIC_CAST_NOTNULL:%.*]]
// CHECK:       dynamic_cast.notnull:
// CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTS5Base2")
// CHECK-NEXT:    call void @llvm.assume(i1 [[TMP2]])
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds i64, ptr [[VTABLE]], i64 -2
// CHECK-NEXT:    [[OFFSET_TO_TOP:%.*]] = load i64, ptr [[TMP3]], align 8
// CHECK-NEXT:    [[TMP4:%.*]] = getelementptr inbounds i8, ptr [[TMP0]], i64 [[OFFSET_TO_TOP]]
// CHECK-NEXT:    br label [[DYNAMIC_CAST_END:%.*]]
// CHECK:       dynamic_cast.null:
// CHECK-NEXT:    br label [[DYNAMIC_CAST_END]]
// CHECK:       dynamic_cast.end:
// CHECK-NEXT:    [[TMP5:%.*]] = phi ptr [ [[TMP4]], [[DYNAMIC_CAST_NOTNULL]] ], [ null, [[DYNAMIC_CAST_NULL]] ]
// CHECK-NEXT:    ret ptr [[TMP5]]
//
void *test2(Base2 *b) {
  return dynamic_cast<void *>(b);
}
