// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// RUN: %clang_cc1 -I%S -triple aarch64-unknown-linux -emit-llvm -fsafe-static-cast -o - %s | FileCheck %s
struct A { virtual void f(); };
struct B : A { };

// CHECK-LABEL: define dso_local noundef ptr @_Z1fP1A(
// CHECK-SAME: ptr noundef [[A:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[TMP0]], null
// CHECK-NEXT:    br i1 [[TMP1]], label %[[DYNAMIC_CAST_NULL:.*]], label %[[DYNAMIC_CAST_NOTNULL:.*]]
// CHECK:       [[DYNAMIC_CAST_NOTNULL]]:
// CHECK-NEXT:    [[TMP2:%.*]] = call ptr @__dynamic_cast(ptr [[TMP0]], ptr @_ZTI1A, ptr @_ZTI1B, i64 0) #[[ATTR2:[0-9]+]]
// CHECK-NEXT:    br label %[[DYNAMIC_CAST_END:.*]]
// CHECK:       [[DYNAMIC_CAST_NULL]]:
// CHECK-NEXT:    br label %[[DYNAMIC_CAST_END]]
// CHECK:       [[DYNAMIC_CAST_END]]:
// CHECK-NEXT:    [[TMP3:%.*]] = phi ptr [ [[TMP2]], %[[DYNAMIC_CAST_NOTNULL]] ], [ null, %[[DYNAMIC_CAST_NULL]] ]
// CHECK-NEXT:    ret ptr [[TMP3]]
//
B *f(A *a) {
  return static_cast<B *>(a);
}

// CHECK-LABEL: define dso_local noundef nonnull align 8 dereferenceable(8) ptr @_Z1fR1A(
// CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[A:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[A_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[A]], ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[A_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = call ptr @__dynamic_cast(ptr [[TMP0]], ptr @_ZTI1A, ptr @_ZTI1B, i64 0) #[[ATTR2]]
// CHECK-NEXT:    [[TMP2:%.*]] = icmp eq ptr [[TMP1]], null
// CHECK-NEXT:    br i1 [[TMP2]], label %[[DYNAMIC_CAST_BAD_CAST:.*]], label %[[DYNAMIC_CAST_END:.*]]
// CHECK:       [[DYNAMIC_CAST_BAD_CAST]]:
// CHECK-NEXT:    call void @__cxa_bad_cast() #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    unreachable
// CHECK:       [[DYNAMIC_CAST_END]]:
// CHECK-NEXT:    ret ptr [[TMP1]]
//
B &f(A &a) {
  return static_cast<B &>(a);
}
