// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 5
// A meta comment on the prefixes:
// ITANIUM-COMMON-MD prefix is common when the options are either non-relative vtable or relative vtables.
// ITANIUM-NO-RV-MD prefix is used when the options specify non-relative vtables, and RV-MD is used when the options specify relative vtables.

// Tests for the cfi-vcall feature:
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -fsanitize-trap=cfi-vcall -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-NVT-NO-RV --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=ITANIUM-NO-RV-MD --check-prefix=TT-ITANIUM-HIDDEN --check-prefix=NDIAG %s
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-NVT-NO-RV --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=ITANIUM-NO-RV-MD --check-prefix=TT-ITANIUM-HIDDEN --check-prefix=ITANIUM-NO-RV-MD-DIAG --check-prefix=ITANIUM-DIAG --check-prefix=DIAG --check-prefix=DIAG-ABORT %s
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -fsanitize-recover=cfi-vcall -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-NVT-NO-RV --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=ITANIUM-NO-RV-MD --check-prefix=TT-ITANIUM-HIDDEN --check-prefix=ITANIUM-NO-RV-MD-DIAG --check-prefix=ITANIUM-DIAG --check-prefix=DIAG --check-prefix=DIAG-RECOVER %s
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-pc-windows-msvc -fsanitize=cfi-vcall -fsanitize-trap=cfi-vcall -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-NVT-NO-RV --check-prefix=MS --check-prefix=MS-TYPEMETADATA --check-prefix=TT-MS --check-prefix=NDIAG %s

// Tests for the whole-program-vtables feature:
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=VTABLE-OPT --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=ITANIUM-NO-RV-MD --check-prefix=TT-ITANIUM-HIDDEN %s
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-unknown-linux -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=VTABLE-OPT --check-prefix=ITANIUM-DEFAULTVIS --check-prefix=TT-ITANIUM-DEFAULT %s
// RUN: %clang_cc1 -O2 -flto -flto-unit -triple x86_64-unknown-linux -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=ITANIUM-OPT --check-prefix=ITANIUM-OPT-LAYOUT %s
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-pc-windows-msvc -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=VTABLE-OPT --check-prefix=MS --check-prefix=MS-TYPEMETADATA --check-prefix=TT-MS %s

// Tests for cfi + whole-program-vtables:
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -fsanitize-trap=cfi-vcall -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-VT --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=TC-ITANIUM --check-prefix=ITANIUM-NO-RV-MD %s
// RUN: %clang_cc1 -flto -flto-unit -triple x86_64-pc-windows-msvc -fsanitize=cfi-vcall -fsanitize-trap=cfi-vcall -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-VT --check-prefix=MS --check-prefix=MS-TYPEMETADATA --check-prefix=TC-MS %s

// Equivalent tests for above, but with relative-vtables.
// Tests for the cfi-vcall feature:
// RUN: %clang_cc1 -fexperimental-relative-c++-abi-vtables -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -fsanitize-trap=cfi-vcall -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-NVT --check-prefix=RV-MD --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=TT-ITANIUM-HIDDEN --check-prefix=NDIAG --check-prefix=CFI-NVT-RV %s
// RUN: %clang_cc1 -fexperimental-relative-c++-abi-vtables -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-NVT --check-prefix=CFI-NVT-RV --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=RV-MD --check-prefix=TT-ITANIUM-HIDDEN --check-prefix=ITANIUM-DIAG --check-prefix=RV-MD-DIAG --check-prefix=DIAG --check-prefix=DIAG-ABORT %s
// RUN: %clang_cc1 -fexperimental-relative-c++-abi-vtables -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -fsanitize-recover=cfi-vcall -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-NVT --check-prefix=CFI-NVT-RV --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=RV-MD --check-prefix=TT-ITANIUM-HIDDEN --check-prefix=ITANIUM-DIAG --check-prefix=RV-MD-DIAG --check-prefix=DIAG --check-prefix=DIAG-RECOVER %s

// Tests for the whole-program-vtables feature:
// RUN: %clang_cc1 -fexperimental-relative-c++-abi-vtables -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=VTABLE-OPT --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD -check-prefix=RV-MD --check-prefix=TT-ITANIUM-HIDDEN %s
// RUN: %clang_cc1 -fexperimental-relative-c++-abi-vtables -flto -flto-unit -triple x86_64-unknown-linux -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=VTABLE-OPT --check-prefix=ITANIUM-DEFAULTVIS --check-prefix=TT-ITANIUM-DEFAULT %s
// RUN: %clang_cc1 -fexperimental-relative-c++-abi-vtables -O2 -flto -flto-unit -triple x86_64-unknown-linux -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=ITANIUM-OPT --check-prefix=RV-OPT-LAYOUT %s

// Tests for cfi + whole-program-vtables:
// RUN: %clang_cc1 -fexperimental-relative-c++-abi-vtables -flto -flto-unit -triple x86_64-unknown-linux -fvisibility=hidden -fsanitize=cfi-vcall -fsanitize-trap=cfi-vcall -fwhole-program-vtables -emit-llvm -o - %s | FileCheck --check-prefix=CFI --check-prefix=CFI-VT --check-prefix=ITANIUM-HIDDEN --check-prefix=ITANIUM-COMMON-MD --check-prefix=RV-MD --check-prefix=TC-ITANIUM %s

// Tests that type metadata are annotated on vtables with `-profile-instrument=llvm` (which is equivalent to clang driver option `-fprofile-generate` without `-fcs-profile-generate`):
// - In clang driver, `-fprofile-instrument` cc1 option is set to 'llvm' iff clang driver option `-fprofile-generate{,=}` is taking effect.
// RUN: %clang_cc1 -fprofile-instrument=llvm -fno-lto -triple x86_64-unknown-linux -emit-llvm %s -o - | FileCheck %s --check-prefix=ITANIUM-COMMON-MD
// RUN: %clang_cc1 -fprofile-instrument=llvm -fno-lto -triple x86_64-pc-windows-msvc -emit-llvm %s -o - | FileCheck %s --check-prefix=MS-TYPEMETADATA

// Tests type metadata are not annotated on vtables if `-fno-lto` is specified and `-fprofile-instrument` is any of {none, clang, csllvm}.
// This is mainly for test coverage; there isn't a fundamental reason type metadata couldn't be annotated with those options.

// RUN: %clang_cc1 -fprofile-instrument=none -fno-lto -triple x86_64-unknown-linux -emit-llvm %s -o - | FileCheck %s --implicit-check-not="!type"
// RUN: %clang_cc1 -fprofile-instrument=clang -fno-lto -triple x86_64-unknown-linux -emit-llvm %s -o - | FileCheck %s --implicit-check-not="!type"
// RUN: %clang_cc1 -fprofile-instrument=csllvm -fno-lto -triple x86_64-unknown-linux -emit-llvm %s -o - | FileCheck %s --implicit-check-not="!type"

// RUN: %clang_cc1 -fprofile-instrument=none -fno-lto -triple x86_64-pc-windows-msvc -emit-llvm %s -o - | FileCheck %s --implicit-check-not="!type"
// RUN: %clang_cc1 -fprofile-instrument=clang -fno-lto -triple x86_64-pc-windows-msvc -emit-llvm %s -o - | FileCheck %s --implicit-check-not="!type"
// RUN: %clang_cc1 -fprofile-instrument=csllvm -fno-lto -triple x86_64-pc-windows-msvc -emit-llvm %s -o - | FileCheck %s --implicit-check-not="!type"











struct A {
  A();
  virtual void f();
};

struct B : virtual A {
  B();
  virtual void g();
  virtual void h();
};

struct C : virtual A {
  C();
};

namespace {

struct D : B, C {
  D();
  virtual void f();
  virtual void h();
};

}

// ITANIUM-HIDDEN-LABEL: define hidden void @_ZN1AC1Ev(
// ITANIUM-HIDDEN-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0:[0-9]+]] align 2 {
// ITANIUM-HIDDEN-NEXT:  [[ENTRY:.*:]]
// ITANIUM-HIDDEN-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-HIDDEN-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// ITANIUM-HIDDEN-NEXT:    ret void
//
// ITANIUM-DEFAULTVIS-LABEL: define dso_local void @_ZN1AC1Ev(
// ITANIUM-DEFAULTVIS-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0:[0-9]+]] align 2 {
// ITANIUM-DEFAULTVIS-NEXT:  [[ENTRY:.*:]]
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-DEFAULTVIS-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// ITANIUM-DEFAULTVIS-NEXT:    ret void
//
// ITANIUM-OPT-LAYOUT-LABEL: define dso_local void @_ZN1AC1Ev(
// ITANIUM-OPT-LAYOUT-SAME: ptr nocapture noundef nonnull writeonly align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0:[0-9]+]] align 2 {
// ITANIUM-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) (i8, ptr @_ZTV1A, i64 16), ptr [[THIS]], align 8, !tbaa [[TBAA29:![0-9]+]]
// ITANIUM-OPT-LAYOUT-NEXT:    ret void
//
// CFI-NVT-LABEL: define hidden void @_ZN1AC1Ev(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0:[0-9]+]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// CFI-NVT-NEXT:    ret void
//
// RV-OPT-LAYOUT-LABEL: define dso_local void @_ZN1AC1Ev(
// RV-OPT-LAYOUT-SAME: ptr nocapture noundef nonnull writeonly align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0:[0-9]+]] align 2 {
// RV-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// RV-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-8, 4) (i8, ptr @_ZTV1A.local, i64 8), ptr [[THIS]], align 8, !tbaa [[TBAA29:![0-9]+]]
// RV-OPT-LAYOUT-NEXT:    ret void
//
// CHECK-LABEL: define dso_local void @_ZN1AC1Ev(
// CHECK-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0:[0-9]+]] align 2 {
// CHECK-NEXT:  [[ENTRY:.*:]]
// CHECK-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CHECK-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CHECK-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// CHECK-NEXT:    ret void
//
A::A() {}
// ITANIUM-NO-RV-MD-LABEL: define hidden void @_ZN1BC1Ev(
// ITANIUM-NO-RV-MD-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-NO-RV-MD-NEXT:  [[ENTRY:.*:]]
// ITANIUM-NO-RV-MD-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-NO-RV-MD-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-NO-RV-MD-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-NO-RV-MD-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// ITANIUM-NO-RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-32, 24) ({ [7 x ptr] }, ptr @_ZTV1B, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// ITANIUM-NO-RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-32, 24) ({ [7 x ptr] }, ptr @_ZTV1B, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// ITANIUM-NO-RV-MD-NEXT:    ret void
//
// ITANIUM-OPT-LAYOUT-LABEL: define dso_local void @_ZN1BC1Ev(
// ITANIUM-OPT-LAYOUT-SAME: ptr nocapture noundef nonnull writeonly align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-32, 24) (i8, ptr @_ZTV1B, i64 32), ptr [[THIS]], align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    ret void
//
// CFI-NVT-LABEL: define hidden void @_ZN1BC1Ev(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// CFI-NVT-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32] }, ptr @_ZTV1B, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// CFI-NVT-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32] }, ptr @_ZTV1B, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// CFI-NVT-NEXT:    ret void
//
// RV-MD-LABEL: define hidden void @_ZN1BC1Ev(
// RV-MD-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// RV-MD-NEXT:  [[ENTRY:.*:]]
// RV-MD-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// RV-MD-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// RV-MD-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// RV-MD-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32] }, ptr @_ZTV1B, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32] }, ptr @_ZTV1B, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// RV-MD-NEXT:    ret void
//
// RV-OPT-LAYOUT-LABEL: define dso_local void @_ZN1BC1Ev(
// RV-OPT-LAYOUT-SAME: ptr nocapture noundef nonnull writeonly align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// RV-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// RV-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) (i8, ptr @_ZTV1B.local, i64 16), ptr [[THIS]], align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    ret void
//
B::B() {}
// ITANIUM-NO-RV-MD-LABEL: define hidden void @_ZN1CC1Ev(
// ITANIUM-NO-RV-MD-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-NO-RV-MD-NEXT:  [[ENTRY:.*:]]
// ITANIUM-NO-RV-MD-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-NO-RV-MD-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-NO-RV-MD-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-NO-RV-MD-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// ITANIUM-NO-RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-32, 8) ({ [5 x ptr] }, ptr @_ZTV1C, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// ITANIUM-NO-RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-32, 8) ({ [5 x ptr] }, ptr @_ZTV1C, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// ITANIUM-NO-RV-MD-NEXT:    ret void
//
// ITANIUM-OPT-LAYOUT-LABEL: define dso_local void @_ZN1CC1Ev(
// ITANIUM-OPT-LAYOUT-SAME: ptr nocapture noundef nonnull writeonly align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-32, 8) (i8, ptr @_ZTV1C, i64 32), ptr [[THIS]], align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    ret void
//
// CFI-NVT-LABEL: define hidden void @_ZN1CC1Ev(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// CFI-NVT-NEXT:    store ptr getelementptr inbounds inrange(-16, 4) ({ [5 x i32] }, ptr @_ZTV1C, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// CFI-NVT-NEXT:    store ptr getelementptr inbounds inrange(-16, 4) ({ [5 x i32] }, ptr @_ZTV1C, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// CFI-NVT-NEXT:    ret void
//
// RV-MD-LABEL: define hidden void @_ZN1CC1Ev(
// RV-MD-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// RV-MD-NEXT:  [[ENTRY:.*:]]
// RV-MD-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// RV-MD-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// RV-MD-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// RV-MD-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-16, 4) ({ [5 x i32] }, ptr @_ZTV1C, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-16, 4) ({ [5 x i32] }, ptr @_ZTV1C, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// RV-MD-NEXT:    ret void
//
// RV-OPT-LAYOUT-LABEL: define dso_local void @_ZN1CC1Ev(
// RV-OPT-LAYOUT-SAME: ptr nocapture noundef nonnull writeonly align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// RV-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// RV-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-16, 4) (i8, ptr @_ZTV1C.local, i64 16), ptr [[THIS]], align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    ret void
//
C::C() {}
// ITANIUM-NO-RV-MD-LABEL: define internal void @_ZN12_GLOBAL__N_11DC1Ev(
// ITANIUM-NO-RV-MD-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-NO-RV-MD-NEXT:  [[ENTRY:.*:]]
// ITANIUM-NO-RV-MD-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-NO-RV-MD-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-NO-RV-MD-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-NO-RV-MD-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// ITANIUM-NO-RV-MD-NEXT:    call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]], ptr noundef getelementptr inbounds ([7 x ptr], ptr @_ZTTN12_GLOBAL__N_11DE, i64 0, i64 1))
// ITANIUM-NO-RV-MD-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i64 8
// ITANIUM-NO-RV-MD-NEXT:    call void @_ZN1CC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[TMP0]], ptr noundef getelementptr inbounds ([7 x ptr], ptr @_ZTTN12_GLOBAL__N_11DE, i64 0, i64 3))
// ITANIUM-NO-RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-32, 24) ({ [7 x ptr], [5 x ptr] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// ITANIUM-NO-RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-32, 24) ({ [7 x ptr], [5 x ptr] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// ITANIUM-NO-RV-MD-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i64 8
// ITANIUM-NO-RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-32, 8) ({ [7 x ptr], [5 x ptr] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 1, i32 4), ptr [[ADD_PTR]], align 8
// ITANIUM-NO-RV-MD-NEXT:    ret void
//
// CFI-NVT-LABEL: define internal void @_ZN12_GLOBAL__N_11DC1Ev(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// CFI-NVT-NEXT:    call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]], ptr noundef getelementptr inbounds ([7 x ptr], ptr @_ZTTN12_GLOBAL__N_11DE, i64 0, i64 1))
// CFI-NVT-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i64 8
// CFI-NVT-NEXT:    call void @_ZN1CC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[TMP0]], ptr noundef getelementptr inbounds ([7 x ptr], ptr @_ZTTN12_GLOBAL__N_11DE, i64 0, i64 3))
// CFI-NVT-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32], [5 x i32] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// CFI-NVT-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32], [5 x i32] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// CFI-NVT-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i32 8
// CFI-NVT-NEXT:    store ptr getelementptr inbounds inrange(-16, 4) ({ [7 x i32], [5 x i32] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 1, i32 4), ptr [[ADD_PTR]], align 8
// CFI-NVT-NEXT:    ret void
//
// RV-MD-LABEL: define internal void @_ZN12_GLOBAL__N_11DC1Ev(
// RV-MD-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// RV-MD-NEXT:  [[ENTRY:.*:]]
// RV-MD-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// RV-MD-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// RV-MD-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// RV-MD-NEXT:    call void @_ZN1AC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]])
// RV-MD-NEXT:    call void @_ZN1BC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[THIS1]], ptr noundef getelementptr inbounds ([7 x ptr], ptr @_ZTTN12_GLOBAL__N_11DE, i64 0, i64 1))
// RV-MD-NEXT:    [[TMP0:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i64 8
// RV-MD-NEXT:    call void @_ZN1CC2Ev(ptr noundef nonnull align 8 dereferenceable(8) [[TMP0]], ptr noundef getelementptr inbounds ([7 x ptr], ptr @_ZTTN12_GLOBAL__N_11DE, i64 0, i64 3))
// RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32], [5 x i32] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-16, 12) ({ [7 x i32], [5 x i32] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 0, i32 4), ptr [[THIS1]], align 8
// RV-MD-NEXT:    [[ADD_PTR:%.*]] = getelementptr inbounds i8, ptr [[THIS1]], i32 8
// RV-MD-NEXT:    store ptr getelementptr inbounds inrange(-16, 4) ({ [7 x i32], [5 x i32] }, ptr @_ZTVN12_GLOBAL__N_11DE, i32 0, i32 1, i32 4), ptr [[ADD_PTR]], align 8
// RV-MD-NEXT:    ret void
//
D::D() {}

// ITANIUM-HIDDEN-LABEL: define hidden void @_ZN1A1fEv(
// ITANIUM-HIDDEN-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-HIDDEN-NEXT:  [[ENTRY:.*:]]
// ITANIUM-HIDDEN-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-HIDDEN-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    ret void
//
// ITANIUM-DEFAULTVIS-LABEL: define dso_local void @_ZN1A1fEv(
// ITANIUM-DEFAULTVIS-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-DEFAULTVIS-NEXT:  [[ENTRY:.*:]]
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-DEFAULTVIS-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    ret void
//
// ITANIUM-OPT-LABEL: define dso_local void @_ZN1A1fEv(
// ITANIUM-OPT-SAME: ptr nocapture nonnull readnone align 8 [[THIS:%.*]]) unnamed_addr #[[ATTR2:[0-9]+]] align 2 {
// ITANIUM-OPT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-NEXT:    ret void
//
// CFI-NVT-LABEL: define hidden void @_ZN1A1fEv(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    ret void
//
void A::f() {
}

// ITANIUM-HIDDEN-LABEL: define hidden void @_ZN1B1gEv(
// ITANIUM-HIDDEN-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-HIDDEN-NEXT:  [[ENTRY:.*:]]
// ITANIUM-HIDDEN-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-HIDDEN-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    ret void
//
// ITANIUM-DEFAULTVIS-LABEL: define dso_local void @_ZN1B1gEv(
// ITANIUM-DEFAULTVIS-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-DEFAULTVIS-NEXT:  [[ENTRY:.*:]]
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-DEFAULTVIS-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    ret void
//
// ITANIUM-OPT-LABEL: define dso_local void @_ZN1B1gEv(
// ITANIUM-OPT-SAME: ptr nocapture nonnull readnone align 8 [[THIS:%.*]]) unnamed_addr #[[ATTR2]] align 2 {
// ITANIUM-OPT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-NEXT:    ret void
//
// CFI-NVT-LABEL: define hidden void @_ZN1B1gEv(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(8) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    ret void
//
void B::g() {
}

// ITANIUM-HIDDEN-LABEL: define internal void @_ZN12_GLOBAL__N_11D1fEv(
// ITANIUM-HIDDEN-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-HIDDEN-NEXT:  [[ENTRY:.*:]]
// ITANIUM-HIDDEN-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-HIDDEN-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    ret void
//
// ITANIUM-DEFAULTVIS-LABEL: define internal void @_ZN12_GLOBAL__N_11D1fEv(
// ITANIUM-DEFAULTVIS-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-DEFAULTVIS-NEXT:  [[ENTRY:.*:]]
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-DEFAULTVIS-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    ret void
//
// ITANIUM-OPT-LABEL: define internal void @_ZN12_GLOBAL__N_11D1fEv(
// ITANIUM-OPT-SAME: ptr nocapture nonnull readnone align 8 [[THIS:%.*]]) unnamed_addr #[[ATTR2]] align 2 {
// ITANIUM-OPT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-NEXT:    ret void
//
// CFI-NVT-LABEL: define internal void @_ZN12_GLOBAL__N_11D1fEv(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    ret void
//
void D::f() {
}

// ITANIUM-HIDDEN-LABEL: define internal void @_ZN12_GLOBAL__N_11D1hEv(
// ITANIUM-HIDDEN-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-HIDDEN-NEXT:  [[ENTRY:.*:]]
// ITANIUM-HIDDEN-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-HIDDEN-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-HIDDEN-NEXT:    ret void
//
// ITANIUM-DEFAULTVIS-LABEL: define internal void @_ZN12_GLOBAL__N_11D1hEv(
// ITANIUM-DEFAULTVIS-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// ITANIUM-DEFAULTVIS-NEXT:  [[ENTRY:.*:]]
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-DEFAULTVIS-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    ret void
//
// ITANIUM-OPT-LABEL: define internal void @_ZN12_GLOBAL__N_11D1hEv(
// ITANIUM-OPT-SAME: ptr nocapture nonnull readnone align 8 [[THIS:%.*]]) unnamed_addr #[[ATTR2]] align 2 {
// ITANIUM-OPT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-NEXT:    ret void
//
// CFI-NVT-LABEL: define internal void @_ZN12_GLOBAL__N_11D1hEv(
// CFI-NVT-SAME: ptr noundef nonnull align 8 dereferenceable(16) [[THIS:%.*]]) unnamed_addr #[[ATTR0]] align 2 {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[THIS_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[THIS]], ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    [[THIS1:%.*]] = load ptr, ptr [[THIS_ADDR]], align 8
// CFI-NVT-NEXT:    ret void
//
void D::h() {
}

// ITANIUM-OPT-LAYOUT-LABEL: define dso_local void @_Z2afP1A(
// ITANIUM-OPT-LAYOUT-SAME: ptr noundef [[A:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// ITANIUM-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[A]], align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.public.type.test(ptr [[VTABLE]], metadata !"_ZTS1A")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTABLE]], align 8
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(8) [[A]]) #[[ATTR8:[0-9]+]]
// ITANIUM-OPT-LAYOUT-NEXT:    ret void
//
// RV-OPT-LAYOUT-LABEL: define dso_local void @_Z2afP1A(
// RV-OPT-LAYOUT-SAME: ptr noundef [[A:%.*]]) local_unnamed_addr #[[ATTR3:[0-9]+]] {
// RV-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// RV-OPT-LAYOUT-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[A]], align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.public.type.test(ptr [[VTABLE]], metadata !"_ZTS1A")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// RV-OPT-LAYOUT-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.load.relative.i32(ptr [[VTABLE]], i32 0)
// RV-OPT-LAYOUT-NEXT:    tail call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(8) [[A]]) #[[ATTR9:[0-9]+]]
// RV-OPT-LAYOUT-NEXT:    ret void
//
void af(A *a) {


#line 123
  a->f();
}

//
void df1(D *d) {
  d->f();
}

//
void dg1(D *d) {
  d->g();
}

//
void dh1(D *d) {
  d->h();
}

__attribute__((no_sanitize("cfi")))
// ITANIUM-NO-RV-MD-DIAG-LABEL: define internal void @_Z3df2PN12_GLOBAL__N_11DE(
// ITANIUM-NO-RV-MD-DIAG-SAME: ptr noundef [[D:%.*]]) #[[ATTR0]] {
// ITANIUM-NO-RV-MD-DIAG-NEXT:  [[ENTRY:.*:]]
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[D_ADDR]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 0
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VFN]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) [[TMP0]])
// ITANIUM-NO-RV-MD-DIAG-NEXT:    ret void
//
// CFI-NVT-LABEL: define internal void @_Z3df2PN12_GLOBAL__N_11DE(
// CFI-NVT-SAME: ptr noundef [[D:%.*]]) #[[ATTR0]] {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8
// CFI-NVT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[D_ADDR]], align 8
// CFI-NVT-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// CFI-NVT-NEXT:    [[TMP1:%.*]] = call ptr @llvm.load.relative.i32(ptr [[VTABLE]], i32 0)
// CFI-NVT-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) [[TMP0]])
// CFI-NVT-NEXT:    ret void
//
void df2(D *d) {
  d->f();
}

__attribute__((no_sanitize("address"))) __attribute__((no_sanitize("cfi-vcall")))
// ITANIUM-NO-RV-MD-DIAG-LABEL: define internal void @_Z3df3PN12_GLOBAL__N_11DE(
// ITANIUM-NO-RV-MD-DIAG-SAME: ptr noundef [[D:%.*]]) #[[ATTR0]] {
// ITANIUM-NO-RV-MD-DIAG-NEXT:  [[ENTRY:.*:]]
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[D_ADDR]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[VFN:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 0
// ITANIUM-NO-RV-MD-DIAG-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VFN]], align 8
// ITANIUM-NO-RV-MD-DIAG-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) [[TMP0]])
// ITANIUM-NO-RV-MD-DIAG-NEXT:    ret void
//
// CFI-NVT-LABEL: define internal void @_Z3df3PN12_GLOBAL__N_11DE(
// CFI-NVT-SAME: ptr noundef [[D:%.*]]) #[[ATTR0]] {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[D_ADDR:%.*]] = alloca ptr, align 8
// CFI-NVT-NEXT:    store ptr [[D]], ptr [[D_ADDR]], align 8
// CFI-NVT-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[D_ADDR]], align 8
// CFI-NVT-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// CFI-NVT-NEXT:    [[TMP1:%.*]] = call ptr @llvm.load.relative.i32(ptr [[VTABLE]], i32 0)
// CFI-NVT-NEXT:    call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) [[TMP0]])
// CFI-NVT-NEXT:    ret void
//
void df3(D *d) {
  d->f();
}

D d;

// ITANIUM-HIDDEN-LABEL: define hidden void @_Z3foov(
// ITANIUM-HIDDEN-SAME: ) #[[ATTR0]] {
// ITANIUM-HIDDEN-NEXT:  [[ENTRY:.*:]]
// ITANIUM-HIDDEN-NEXT:    [[FA:%.*]] = alloca [[STRUCT_FA:%.*]], align 8
// ITANIUM-HIDDEN-NEXT:    call void @_Z3df1PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-HIDDEN-NEXT:    call void @_Z3dg1PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-HIDDEN-NEXT:    call void @_Z3dh1PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-HIDDEN-NEXT:    call void @_Z3df2PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-HIDDEN-NEXT:    call void @_Z3df3PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-HIDDEN-NEXT:    call void @_ZZ3foovEN2FAC1Ev(ptr noundef nonnull align 8 dereferenceable(8) [[FA]])
// ITANIUM-HIDDEN-NEXT:    call void @_Z2afP1A(ptr noundef [[FA]])
// ITANIUM-HIDDEN-NEXT:    ret void
//
// ITANIUM-DEFAULTVIS-LABEL: define dso_local void @_Z3foov(
// ITANIUM-DEFAULTVIS-SAME: ) #[[ATTR0]] {
// ITANIUM-DEFAULTVIS-NEXT:  [[ENTRY:.*:]]
// ITANIUM-DEFAULTVIS-NEXT:    [[FA:%.*]] = alloca [[STRUCT_FA:%.*]], align 8
// ITANIUM-DEFAULTVIS-NEXT:    call void @_Z3df1PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-DEFAULTVIS-NEXT:    call void @_Z3dg1PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-DEFAULTVIS-NEXT:    call void @_Z3dh1PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-DEFAULTVIS-NEXT:    call void @_Z3df2PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-DEFAULTVIS-NEXT:    call void @_Z3df3PN12_GLOBAL__N_11DE(ptr noundef @d)
// ITANIUM-DEFAULTVIS-NEXT:    call void @_ZZ3foovEN2FAC1Ev(ptr noundef nonnull align 8 dereferenceable(8) [[FA]])
// ITANIUM-DEFAULTVIS-NEXT:    call void @_Z2afP1A(ptr noundef [[FA]])
// ITANIUM-DEFAULTVIS-NEXT:    ret void
//
// ITANIUM-OPT-LAYOUT-LABEL: define dso_local void @_Z3foov(
// ITANIUM-OPT-LAYOUT-SAME: ) local_unnamed_addr #[[ATTR3]] {
// ITANIUM-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[VTABLE_I:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VTABLE_I]], align 8
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[VTABLE_I1:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP2:%.*]] = tail call i1 @llvm.public.type.test(ptr [[VTABLE_I1]], metadata !"_ZTS1B")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP2]])
// ITANIUM-OPT-LAYOUT-NEXT:    [[VFN_I:%.*]] = getelementptr inbounds i8, ptr [[VTABLE_I1]], i64 8
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP3:%.*]] = load ptr, ptr [[VFN_I]], align 8
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void [[TMP3]](ptr noundef nonnull align 8 dereferenceable(8) @d) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[VTABLE_I2:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP4:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I2]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP4]])
// ITANIUM-OPT-LAYOUT-NEXT:    [[VFN_I3:%.*]] = getelementptr inbounds i8, ptr [[VTABLE_I2]], i64 16
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP5:%.*]] = load ptr, ptr [[VFN_I3]], align 8
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void [[TMP5]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[VTABLE_I4:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP6:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I4]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP6]])
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP7:%.*]] = load ptr, ptr [[VTABLE_I4]], align 8
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void [[TMP7]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[VTABLE_I5:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP8:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I5]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP8]])
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP9:%.*]] = load ptr, ptr [[VTABLE_I5]], align 8
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void [[TMP9]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP10:%.*]] = tail call i1 @llvm.public.type.test(ptr nonnull getelementptr inbounds inrange(-16, 8) (i8, ptr @_ZTVZ3foovE2FA, i64 16), metadata !"_ZTS1A")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP10]])
// ITANIUM-OPT-LAYOUT-NEXT:    ret void
//
// CFI-NVT-LABEL: define hidden void @_Z3foov(
// CFI-NVT-SAME: ) #[[ATTR0]] {
// CFI-NVT-NEXT:  [[ENTRY:.*:]]
// CFI-NVT-NEXT:    [[FA:%.*]] = alloca [[STRUCT_FA:%.*]], align 8
// CFI-NVT-NEXT:    call void @_Z3df1PN12_GLOBAL__N_11DE(ptr noundef @d)
// CFI-NVT-NEXT:    call void @_Z3dg1PN12_GLOBAL__N_11DE(ptr noundef @d)
// CFI-NVT-NEXT:    call void @_Z3dh1PN12_GLOBAL__N_11DE(ptr noundef @d)
// CFI-NVT-NEXT:    call void @_Z3df2PN12_GLOBAL__N_11DE(ptr noundef @d)
// CFI-NVT-NEXT:    call void @_Z3df3PN12_GLOBAL__N_11DE(ptr noundef @d)
// CFI-NVT-NEXT:    call void @_ZZ3foovEN2FAC1Ev(ptr noundef nonnull align 8 dereferenceable(8) [[FA]])
// CFI-NVT-NEXT:    call void @_Z2afP1A(ptr noundef [[FA]])
// CFI-NVT-NEXT:    ret void
//
// RV-OPT-LAYOUT-LABEL: define dso_local void @_Z3foov(
// RV-OPT-LAYOUT-SAME: ) local_unnamed_addr #[[ATTR3]] {
// RV-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// RV-OPT-LAYOUT-NEXT:    [[FA:%.*]] = alloca [[STRUCT_FA:%.*]], align 8
// RV-OPT-LAYOUT-NEXT:    [[VTABLE_I:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// RV-OPT-LAYOUT-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.load.relative.i32(ptr [[VTABLE_I]], i32 0)
// RV-OPT-LAYOUT-NEXT:    tail call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    [[VTABLE_I1:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP2:%.*]] = tail call i1 @llvm.public.type.test(ptr [[VTABLE_I1]], metadata !"_ZTS1B")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP2]])
// RV-OPT-LAYOUT-NEXT:    [[TMP3:%.*]] = tail call ptr @llvm.load.relative.i32(ptr [[VTABLE_I1]], i32 4)
// RV-OPT-LAYOUT-NEXT:    tail call void [[TMP3]](ptr noundef nonnull align 8 dereferenceable(8) @d) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    [[VTABLE_I2:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP4:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I2]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP4]])
// RV-OPT-LAYOUT-NEXT:    [[TMP5:%.*]] = tail call ptr @llvm.load.relative.i32(ptr [[VTABLE_I2]], i32 8)
// RV-OPT-LAYOUT-NEXT:    tail call void [[TMP5]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    [[VTABLE_I3:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP6:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I3]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP6]])
// RV-OPT-LAYOUT-NEXT:    [[TMP7:%.*]] = tail call ptr @llvm.load.relative.i32(ptr [[VTABLE_I3]], i32 0)
// RV-OPT-LAYOUT-NEXT:    tail call void [[TMP7]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    [[VTABLE_I4:%.*]] = load ptr, ptr @d, align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP8:%.*]] = tail call i1 @llvm.type.test(ptr [[VTABLE_I4]], metadata !"_ZTSN12_GLOBAL__N_11DE")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP8]])
// RV-OPT-LAYOUT-NEXT:    [[TMP9:%.*]] = tail call ptr @llvm.load.relative.i32(ptr [[VTABLE_I4]], i32 0)
// RV-OPT-LAYOUT-NEXT:    tail call void [[TMP9]](ptr noundef nonnull align 8 dereferenceable(16) @d) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr nonnull [[FA]]) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-8, 4) (i8, ptr @_ZTVZ3foovE2FA, i64 8), ptr [[FA]], align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP10:%.*]] = tail call i1 @llvm.public.type.test(ptr nonnull getelementptr inbounds inrange(-8, 4) (i8, ptr @_ZTVZ3foovE2FA, i64 8), metadata !"_ZTS1A")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP10]])
// RV-OPT-LAYOUT-NEXT:    call void dso_local_equivalent @_ZZ3foovEN2FA1fEv(ptr noundef nonnull align 8 dereferenceable(8) [[FA]]) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    call void @llvm.lifetime.end.p0(i64 8, ptr nonnull [[FA]]) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    ret void
//
void foo() {
  df1(&d);
  dg1(&d);
  dh1(&d);
  df2(&d);
  df3(&d);

  struct FA : A {
    void f() {}
  } fa;
  af(&fa);
}

namespace test2 {

struct A {
  virtual void m_fn1();
};
struct B {
  virtual void m_fn2();
};
struct C : B, A {};
struct D : C {
  void m_fn1();
};

// ITANIUM-OPT-LAYOUT-LABEL: define dso_local void @_ZN5test21fEPNS_1DE(
// ITANIUM-OPT-LAYOUT-SAME: ptr noundef [[D:%.*]]) local_unnamed_addr #[[ATTR3]] {
// ITANIUM-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[D]], align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.public.type.test(ptr [[VTABLE]], metadata !"_ZTSN5test21DE")
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// ITANIUM-OPT-LAYOUT-NEXT:    [[VFN:%.*]] = getelementptr inbounds i8, ptr [[VTABLE]], i64 8
// ITANIUM-OPT-LAYOUT-NEXT:    [[TMP1:%.*]] = load ptr, ptr [[VFN]], align 8
// ITANIUM-OPT-LAYOUT-NEXT:    tail call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) [[D]]) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    ret void
//
// RV-OPT-LAYOUT-LABEL: define dso_local void @_ZN5test21fEPNS_1DE(
// RV-OPT-LAYOUT-SAME: ptr noundef [[D:%.*]]) local_unnamed_addr #[[ATTR3]] {
// RV-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// RV-OPT-LAYOUT-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[D]], align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    [[TMP0:%.*]] = tail call i1 @llvm.public.type.test(ptr [[VTABLE]], metadata !"_ZTSN5test21DE")
// RV-OPT-LAYOUT-NEXT:    tail call void @llvm.assume(i1 [[TMP0]])
// RV-OPT-LAYOUT-NEXT:    [[TMP1:%.*]] = tail call ptr @llvm.load.relative.i32(ptr [[VTABLE]], i32 4)
// RV-OPT-LAYOUT-NEXT:    tail call void [[TMP1]](ptr noundef nonnull align 8 dereferenceable(16) [[D]]) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    ret void
//
void f(D *d) {
  d->m_fn1();
}

}

namespace test3 {
// All virtual functions are outline, so we can assume that it will
// be generated in translation unit where foo is defined.
struct E {
  virtual void foo();
};

// ITANIUM-OPT-LAYOUT-LABEL: define dso_local void @_ZN5test31gEv(
// ITANIUM-OPT-LAYOUT-SAME: ) local_unnamed_addr #[[ATTR3]] {
// ITANIUM-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// ITANIUM-OPT-LAYOUT-NEXT:    [[E:%.*]] = alloca %"struct.test3::E", align 8
// ITANIUM-OPT-LAYOUT-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr nonnull [[E]]) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-16, 8) (i8, ptr @_ZTVN5test31EE, i64 16), ptr [[E]], align 8, !tbaa [[TBAA29]]
// ITANIUM-OPT-LAYOUT-NEXT:    call void @_ZN5test31E3fooEv(ptr noundef nonnull align 8 dereferenceable(8) [[E]]) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    call void @llvm.lifetime.end.p0(i64 8, ptr nonnull [[E]]) #[[ATTR8]]
// ITANIUM-OPT-LAYOUT-NEXT:    ret void
//
// RV-OPT-LAYOUT-LABEL: define dso_local void @_ZN5test31gEv(
// RV-OPT-LAYOUT-SAME: ) local_unnamed_addr #[[ATTR3]] {
// RV-OPT-LAYOUT-NEXT:  [[ENTRY:.*:]]
// RV-OPT-LAYOUT-NEXT:    [[E:%.*]] = alloca %"struct.test3::E", align 8
// RV-OPT-LAYOUT-NEXT:    call void @llvm.lifetime.start.p0(i64 8, ptr nonnull [[E]]) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    store ptr getelementptr inbounds inrange(-8, 4) (i8, ptr @_ZTVN5test31EE, i64 8), ptr [[E]], align 8, !tbaa [[TBAA29]]
// RV-OPT-LAYOUT-NEXT:    call void @_ZN5test31E3fooEv(ptr noundef nonnull align 8 dereferenceable(8) [[E]]) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    call void @llvm.lifetime.end.p0(i64 8, ptr nonnull [[E]]) #[[ATTR9]]
// RV-OPT-LAYOUT-NEXT:    ret void
//
void g() {
  E e;
  e.foo();
}

}  // Test9




//.
// ITANIUM-OPT-LAYOUT: [[TBAA29]] = !{[[META30:![0-9]+]], [[META30]], i64 0}
// ITANIUM-OPT-LAYOUT: [[META30]] = !{!"vtable pointer", [[META31:![0-9]+]], i64 0}
// ITANIUM-OPT-LAYOUT: [[META31]] = !{!"Simple C++ TBAA"}
//.
// RV-OPT-LAYOUT: [[TBAA29]] = !{[[META30:![0-9]+]], [[META30]], i64 0}
// RV-OPT-LAYOUT: [[META30]] = !{!"vtable pointer", [[META31:![0-9]+]], i64 0}
// RV-OPT-LAYOUT: [[META31]] = !{!"Simple C++ TBAA"}
//.
//// NOTE: These prefixes are unused and the list is autogenerated. Do not add tests below this line:
// CFI: {{.*}}
// CFI-NVT-NO-RV: {{.*}}
// CFI-NVT-RV: {{.*}}
// CFI-VT: {{.*}}
// DIAG: {{.*}}
// DIAG-ABORT: {{.*}}
// DIAG-RECOVER: {{.*}}
// ITANIUM-COMMON-MD: {{.*}}
// ITANIUM-DIAG: {{.*}}
// MS: {{.*}}
// MS-TYPEMETADATA: {{.*}}
// NDIAG: {{.*}}
// RV-MD-DIAG: {{.*}}
// TC-ITANIUM: {{.*}}
// TC-MS: {{.*}}
// TT-ITANIUM-DEFAULT: {{.*}}
// TT-ITANIUM-HIDDEN: {{.*}}
// TT-MS: {{.*}}
// VTABLE-OPT: {{.*}}
