// NOTE: Assertions have been autogenerated by utils/update_cc_test_checks.py UTC_ARGS: --version 4
// RUN: %clang_cc1 -I%S -triple aarch64-unknown-linux -flto -fwhole-program-vtables -emit-llvm -o - %s | FileCheck %s
//
#include <typeinfo>
struct Base {};
struct Derived : Base {};

struct Base2 { virtual void foo() {} };
struct Derived2 : Base2 {};

struct __attribute__ ((visibility("hidden"))) Base3 { virtual void foo() {} };
struct __attribute__ ((visibility("hidden"))) Derived3 : Base2 {};

// CHECK-LABEL: define dso_local void @_Z5test1P4Base(
// CHECK-SAME: ptr noundef [[B:%.*]]) #[[ATTR0:[0-9]+]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    ret void
//
void test1(Base *b) {
  typeid(*b);
}

// TODO: emit llvm.public.type.test
// CHECK-LABEL: define dso_local void @_Z5test2P5Base2(
// CHECK-SAME: ptr noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[TMP0]], null
// CHECK-NEXT:    br i1 [[TMP1]], label [[TYPEID_BAD_TYPEID:%.*]], label [[TYPEID_END:%.*]]
// CHECK:       typeid.bad_typeid:
// CHECK-NEXT:    call void @__cxa_bad_typeid() #[[ATTR3:[0-9]+]]
// CHECK-NEXT:    unreachable
// CHECK:       typeid.end:
// CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.public.type.test(ptr [[VTABLE]], metadata !"_ZTS5Base2")
// CHECK-NEXT:    call void @llvm.assume(i1 [[TMP2]])
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 -1
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// CHECK-NEXT:    ret void
//
void test2(Base2 *b) {
  typeid(*b);
}

// TODO: emit llvm.type.test
// CHECK-LABEL: define dso_local void @_Z5test3P5Base3(
// CHECK-SAME: ptr noundef [[B:%.*]]) #[[ATTR0]] {
// CHECK-NEXT:  entry:
// CHECK-NEXT:    [[B_ADDR:%.*]] = alloca ptr, align 8
// CHECK-NEXT:    store ptr [[B]], ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP0:%.*]] = load ptr, ptr [[B_ADDR]], align 8
// CHECK-NEXT:    [[TMP1:%.*]] = icmp eq ptr [[TMP0]], null
// CHECK-NEXT:    br i1 [[TMP1]], label [[TYPEID_BAD_TYPEID:%.*]], label [[TYPEID_END:%.*]]
// CHECK:       typeid.bad_typeid:
// CHECK-NEXT:    call void @__cxa_bad_typeid() #[[ATTR3]]
// CHECK-NEXT:    unreachable
// CHECK:       typeid.end:
// CHECK-NEXT:    [[VTABLE:%.*]] = load ptr, ptr [[TMP0]], align 8
// CHECK-NEXT:    [[TMP2:%.*]] = call i1 @llvm.type.test(ptr [[VTABLE]], metadata !"_ZTS5Base3")
// CHECK-NEXT:    call void @llvm.assume(i1 [[TMP2]])
// CHECK-NEXT:    [[TMP3:%.*]] = getelementptr inbounds ptr, ptr [[VTABLE]], i64 -1
// CHECK-NEXT:    [[TMP4:%.*]] = load ptr, ptr [[TMP3]], align 8
// CHECK-NEXT:    ret void
//
void test3(Base3 *b) {
  typeid(*b);
}
